#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-only
# Hermetic V4-ROLLBACK-REAL-CRASH gate. The public launcher is generated by
# the real generator; only fixture children and a byte-pinned host splash are
# substituted. Every process-bearing assertion runs in a sealed PID/user/mount
# namespace and every timeout/cleanup operation is tied to PID + starttime.
set -euo pipefail

TEST_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)
PROJECT_ROOT=$(cd -- "$TEST_DIR/.." && pwd -P)
# shellcheck source=private-pid-namespace.sh
source "$TEST_DIR/private-pid-namespace.sh"

# Unlike the owner-wide isolated suite, this gate is directly runnable. It
# enters the same fail-closed namespace shape when invoked on its own, while an
# already isolated suite invocation reuses the sealed namespace.
if [[ ${NXBOOTSTRAP_TEST_PRIVATE_PID_NS:-0} != 1 ]]; then
  [[ ${1:-} != --inside-private-pid-namespace ]] || exit 77
  command -v unshare >/dev/null 2>&1 || {
    printf 'v4 rollback real crash test: SKIP (unshare is unavailable)\n' >&2
    exit 77
  }
  exec {host_pid_ns_fd}</proc/self/ns/pid || exit 77
  exec {host_user_ns_fd}</proc/self/ns/user || exit 77
  exec {host_mount_ns_fd}</proc/self/ns/mnt || exit 77
  host_pid_ns=$(readlink "/proc/self/fd/$host_pid_ns_fd" 2>/dev/null || true)
  host_user_ns=$(readlink "/proc/self/fd/$host_user_ns_fd" 2>/dev/null || true)
  host_mount_ns=$(readlink "/proc/self/fd/$host_mount_ns_fd" 2>/dev/null || true)
  [[ -n $host_pid_ns && -n $host_user_ns && -n $host_mount_ns ]] || exit 77
  namespace_guard=$(mktemp -d "${TMPDIR:-/tmp}/nxbootstrap-v4crash-ns.XXXXXX")
  namespace_marker=$namespace_guard/entered
  namespace_cleanup() {
    case $namespace_guard in
      "${TMPDIR:-/tmp}"/nxbootstrap-v4crash-ns.*)
        rm -rf -- "$namespace_guard"
        ;;
    esac
  }
  trap namespace_cleanup EXIT INT TERM
  set +e
  NXBOOTSTRAP_TEST_PRIVATE_PID_NS=1 \
  NXBOOTSTRAP_TEST_HOST_PID_NS=$host_pid_ns \
  NXBOOTSTRAP_TEST_HOST_USER_NS=$host_user_ns \
  NXBOOTSTRAP_TEST_HOST_MOUNT_NS=$host_mount_ns \
  NXBOOTSTRAP_TEST_HOST_PID_NS_FD=$host_pid_ns_fd \
  NXBOOTSTRAP_TEST_HOST_USER_NS_FD=$host_user_ns_fd \
  NXBOOTSTRAP_TEST_HOST_MOUNT_NS_FD=$host_mount_ns_fd \
  NXBOOTSTRAP_TEST_NAMESPACE_MARKER=$namespace_marker \
    unshare --user --map-root-user --pid --fork --kill-child=KILL \
      --mount-proc bash "$0" --inside-private-pid-namespace
  namespace_status=$?
  set -e
  [[ -f $namespace_marker ]] || {
    printf 'v4 rollback real crash test: SKIP (private namespace did not start)\n' >&2
    exit 77
  }
  exit "$namespace_status"
fi

if [[ ${1:-} == --inside-private-pid-namespace ]]; then
  [[ $$ -eq 1 && -n ${NXBOOTSTRAP_TEST_NAMESPACE_MARKER:-} ]] || exit 77
  printf 'entered\n' > "$NXBOOTSTRAP_TEST_NAMESPACE_MARKER"
fi
nxbootstrap_require_private_pid_namespace || exit $?

for required in python3 sha256sum flock mount umount; do
  command -v "$required" >/dev/null 2>&1 || {
    printf 'v4 rollback real crash test refused: %s is required\n' "$required" >&2
    exit 77
  }
done

monotonic_ns() {
  local uptime seconds fraction
  IFS=' ' read -r uptime _ < /proc/uptime || return 1
  seconds=${uptime%%.*}
  fraction=${uptime#*.}000000000
  fraction=${fraction:0:9}
  printf '%s\n' "$((10#$seconds * 1000000000 + 10#$fraction))"
}

proc_state_starttime() {
  local pid=$1 proc_stat rest
  IFS= read -r proc_stat < "/proc/$pid/stat" 2>/dev/null || return 1
  rest=${proc_stat##*) }
  set -- $rest
  [[ $# -ge 20 ]] || return 1
  printf '%s %s\n' "$1" "${20}"
}

proc_exact_alive() {
  local pid=$1 expected_start=$2 identity state start
  builtin kill -0 "$pid" 2>/dev/null || return 1
  identity=$(proc_state_starttime "$pid") || return 1
  read -r state start <<< "$identity"
  [[ $state != Z && $state != X && $start == "$expected_start" ]]
}

terminate_exact() {
  local pid=$1 expected_start=$2 deadline now
  proc_exact_alive "$pid" "$expected_start" || return 1
  builtin kill -TERM "$pid" 2>/dev/null || true
  deadline=$(( $(monotonic_ns) + 500000000 ))
  while proc_exact_alive "$pid" "$expected_start"; do
    now=$(monotonic_ns)
    (( now < deadline )) || break
    sleep 0.02
  done
  if proc_exact_alive "$pid" "$expected_start"; then
    builtin kill -KILL "$pid" 2>/dev/null || true
  fi
  return 0
}

WAIT_STATUS=0
WAIT_TIMED_OUT=0
wait_exact_deadline() {
  local pid=$1 expected_start=$2 deadline=$3 now
  WAIT_TIMED_OUT=0
  while proc_exact_alive "$pid" "$expected_start"; do
    now=$(monotonic_ns)
    if (( now >= deadline )); then
      WAIT_TIMED_OUT=1
      terminate_exact "$pid" "$expected_start" || true
      break
    fi
    sleep 0.02
  done
  set +e
  wait "$pid"
  WAIT_STATUS=$?
  set -e
}

TEST_ROOT=$(mktemp -d "${TMPDIR:-/tmp}/nxbootstrap-v4crash.XXXXXX")
CURRENT_ATTEMPT_DIR=
ROLLBACK_STORE_MOUNTED=0
declare -a OWNED_PIDS=()
declare -a OWNED_STARTTIMES=()

track_owned_pid() {
  OWNED_PIDS+=("$1")
  OWNED_STARTTIMES+=("$2")
}

untrack_owned_pid() {
  local target=$1 index
  for ((index=0; index<${#OWNED_PIDS[@]}; index++)); do
    if [[ ${OWNED_PIDS[index]} == "$target" ]]; then
      OWNED_PIDS[index]=
      OWNED_STARTTIMES[index]=
    fi
  done
}

cleanup() {
  local status=$? index pid start
  trap - EXIT INT TERM
  if [[ $ROLLBACK_STORE_MOUNTED == 1 && -n ${NXRUNTIME_DIR:-} ]]; then
    mount -o remount,bind,rw "$NXRUNTIME_DIR" 2>/dev/null || true
    umount "$NXRUNTIME_DIR" 2>/dev/null || true
  fi
  for ((index=0; index<${#OWNED_PIDS[@]}; index++)); do
    pid=${OWNED_PIDS[index]:-}
    start=${OWNED_STARTTIMES[index]:-}
    [[ -n $pid && -n $start ]] || continue
    terminate_exact "$pid" "$start" || true
    wait "$pid" 2>/dev/null || true
  done
  case $TEST_ROOT in
    "${TMPDIR:-/tmp}"/nxbootstrap-v4crash.*) rm -rf -- "$TEST_ROOT" ;;
    *) status=1 ;;
  esac
  exit "$status"
}
trap cleanup EXIT INT TERM

fail() {
  printf 'v4 rollback real crash test failed: %s\n' "$*" >&2
  if [[ -n $CURRENT_ATTEMPT_DIR && -d $CURRENT_ATTEMPT_DIR ]]; then
    printf '%s\n' '--- attempt artifacts ---' >&2
    find "$CURRENT_ATTEMPT_DIR" -maxdepth 1 -type f -printf '%f\n' \
      2>/dev/null | sort >&2 || true
  fi
  if [[ -n ${LOG:-} && -f $LOG ]]; then
    printf '%s\n' '--- current launcher log (bounded) ---' >&2
    sed -n '1,220p' "$LOG" >&2 || true
  fi
  exit 1
}

# Force the fixture PortMaster control root. These mounts are private to this
# test and can never cover a host/device path.
for masked in /opt /boot /storage/roms/ports /roms/ports; do
  if [[ -d $masked ]]; then
    mount -t tmpfs -o size=64k,mode=0755 tmpfs "$masked" 2>/dev/null ||
      fail "cannot mask preferred PortMaster root $masked"
  fi
done

REAL_ROOT=$TEST_ROOT/real
PORTS_DIR=$REAL_ROOT/roms/ports
PM_DIR=$TEST_ROOT/xdg/PortMaster
MARKERS=$TEST_ROOT/markers
RUNTIME_DIR=$TEST_ROOT/runtime-private
ATTEMPTS=$TEST_ROOT/attempts
mkdir -p "$PORTS_DIR" "$PM_DIR" "$MARKERS" "$ATTEMPTS"
mkdir -m 0700 "$RUNTIME_DIR"

cat > "$PM_DIR/control.txt" <<CONTROL
directory="${TEST_ROOT#/}/real/roms"
ESUDO=""
CUR_TTY=/dev/null
CFW_NAME=v4-rollback-real-crash-fixture
sdl_controllerconfig=""
pm_finish() { printf 'finish\n' >> "$MARKERS/pm-finish"; }
CONTROL

PORT_ID=v4-rollback-port
LAUNCHER_NAME='V4 Rollback.sh'
PORT_DIR=$PORTS_DIR/$PORT_ID
LAUNCHER=$PORTS_DIR/$LAUNCHER_NAME
LOG=$PORT_DIR/log.txt
EVENTS=$PORT_DIR/events.jsonl
PHASE=$PORT_DIR/nxphase-result.json
NXRUNTIME_DIR=$PORT_DIR/.nxruntime
STATE=$NXRUNTIME_DIR/state.json
EXCLUSIVE_RUNTIME_LOCK=$TEST_ROOT/runtime-exclusive.flock
FIXTURE_TOKEN=v4rollback-$RANDOM-$$

write_runtime() {
  local root=$1 label=$2
  mkdir -p "$root"
  printf '%s\n' '#!/usr/bin/env bash' 'set -u' "BUILD_LABEL='$label'" \
    > "$root/rollback-loader"
  cat >> "$root/rollback-loader" <<'STUB'
mode=${NXROLLBACK_MODE:-SUCCESS}

proc_starttime() {
  local proc_stat rest
  IFS= read -r proc_stat < "/proc/$$/stat" || exit 80
  rest=${proc_stat##*) }
  set -- $rest
  [ "$#" -ge 20 ] || exit 80
  printf '%s\n' "${20}"
}

write_health() {
  local receipt_run=$1 health_tmp
  health_tmp="$NXBOOTSTRAP_HEALTH_FILE.tmp.runtime.$$"
  (umask 077; set -C; printf '%s\n' \
    "{\"schema\":\"$NXBOOTSTRAP_HEALTH_SCHEMA\",\"schema_version\":$NXBOOTSTRAP_HEALTH_SCHEMA_VERSION,\"run_id\":\"$receipt_run\",\"generation\":\"$NXBOOTSTRAP_HEALTH_GENERATION\",\"port_id\":\"$NXBOOTSTRAP_HEALTH_PORT_ID\",\"status\":\"ready\"}" \
    > "$health_tmp") || exit 81
  mv -f -- "$health_tmp" "$NXBOOTSTRAP_HEALTH_FILE" || exit 81
}

exec 8>>"$NXROLLBACK_EXCLUSIVE_LOCK" || exit 82
if ! flock -n 8; then
  printf '{"build":"%s","mode":"%s","pid":%s,"ppid":%s,"starttime":"%s","run_id":"%s","generation":"%s","health_file":"%s","receipt_run_id":"","overlap":true}\n' \
    "$BUILD_LABEL" "$mode" "$$" "$PPID" "$(proc_starttime)" \
    "$NXBOOTSTRAP_HEALTH_RUN_ID" "$NXBOOTSTRAP_HEALTH_GENERATION" \
    "$NXBOOTSTRAP_HEALTH_FILE" >> "$NXROLLBACK_TRACE"
  exit 97
fi

receipt_run_id=
case $mode in
  STALE_RECEIPT) receipt_run_id=foreign-run ;;
  RECYCLED_PID_RECEIPT)
    receipt_run_id="$NXBOOTSTRAP_HEALTH_PORT_ID-$PPID-recycled-pid-stale"
    ;;
  LATE_RECEIPT|SUCCESS|HOLD) receipt_run_id=$NXBOOTSTRAP_HEALTH_RUN_ID ;;
esac
child_start=$(proc_starttime)
printf '{"build":"%s","mode":"%s","pid":%s,"ppid":%s,"starttime":"%s","run_id":"%s","generation":"%s","health_file":"%s","receipt_run_id":"%s","overlap":false}\n' \
  "$BUILD_LABEL" "$mode" "$$" "$PPID" "$child_start" \
  "$NXBOOTSTRAP_HEALTH_RUN_ID" "$NXBOOTSTRAP_HEALTH_GENERATION" \
  "$NXBOOTSTRAP_HEALTH_FILE" "$receipt_run_id" >> "$NXROLLBACK_TRACE"

case $mode in
  ABRT) builtin kill -ABRT "$$"; exit 98 ;;
  TERM) builtin kill -TERM "$$"; exit 98 ;;
  EXIT) exit 42 ;;
  STALE_RECEIPT|RECYCLED_PID_RECEIPT)
    write_health "$receipt_run_id"
    exit 0
    ;;
  LATE_RECEIPT)
    request_tmp="$NXROLLBACK_LATE_REQUEST.tmp.$$"
    (umask 077; set -C
      printf '%s\n' "$NXBOOTSTRAP_HEALTH_FILE" \
        "{\"schema\":\"$NXBOOTSTRAP_HEALTH_SCHEMA\",\"schema_version\":$NXBOOTSTRAP_HEALTH_SCHEMA_VERSION,\"run_id\":\"$NXBOOTSTRAP_HEALTH_RUN_ID\",\"generation\":\"$NXBOOTSTRAP_HEALTH_GENERATION\",\"port_id\":\"$NXBOOTSTRAP_HEALTH_PORT_ID\",\"status\":\"ready\"}" \
        "$$" "$child_start" > "$request_tmp" &&
      mv -f -- "$request_tmp" "$NXROLLBACK_LATE_REQUEST") || exit 83
    exit 42
    ;;
  HOLD)
    hold_ticks=0
    while [ ! -f "$NXROLLBACK_RELEASE_FILE" ] && [ "$hold_ticks" -lt 600 ]; do
      sleep 0.01
      hold_ticks=$((hold_ticks + 1))
    done
    [ -f "$NXROLLBACK_RELEASE_FILE" ] || exit 84
    write_health "$NXBOOTSTRAP_HEALTH_RUN_ID"
    exit 0
    ;;
  SUCCESS)
    write_health "$NXBOOTSTRAP_HEALTH_RUN_ID"
    exit 0
    ;;
  SHOULD_NOT_RUN) exit 99 ;;
  *) exit 85 ;;
esac
STUB
  chmod 0755 "$root/rollback-loader"
}

write_manifest() {
  local target=$1 runtime_root=$2 title=$3 runtime_hash
  runtime_hash=$(sha256sum "$runtime_root/rollback-loader")
  runtime_hash=${runtime_hash%% *}
  cat > "$target" <<JSON
{
  "schema_version": 3,
  "id": "$PORT_ID",
  "title": "$title",
  "launcher_name": "$LAUNCHER_NAME",
  "architecture": "aarch64",
  "executable": "rollback-loader",
  "argument_mode": "none",
  "home_mode": "preserve",
  "nxextract": {"mode": "no", "version": "1.3.0"},
  "required_files": ["rollback-loader"],
  "private_library_paths": [],
  "prepare_script": "",
  "required_capabilities": [],
  "enabled_quirks": [],
  "runtime_report": "log",
  "generation_runtime": [
    {"role":"executable","path":"rollback-loader","mode":"0755","sha256":"$runtime_hash"}
  ]
}
JSON
}

generate_fixture() {
  python3 -B - "$PROJECT_ROOT/tools/generate-port.py" "$TEST_DIR/splash-stub.sh" \
    "$1" "$2" "$3" <<'PY'
import hashlib
import importlib.util
import sys
from pathlib import Path

generator_path, splash_path, manifest_path, output_path, runtime_root = sys.argv[1:]
spec = importlib.util.spec_from_file_location("v4_rollback_fixture", generator_path)
module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(module)
splash = Path(splash_path).resolve()
digest = hashlib.sha256(splash.read_bytes()).hexdigest()
module.nxsplash_artifact = lambda _architecture: (splash, digest)
module.generate(Path(manifest_path), Path(output_path), False, Path(runtime_root))
PY
}

RUNTIME_A=$TEST_ROOT/runtime-a
RUNTIME_B=$TEST_ROOT/runtime-b
GEN_A=$TEST_ROOT/generated-a
GEN_B=$TEST_ROOT/generated-b
write_runtime "$RUNTIME_A" A
write_runtime "$RUNTIME_B" B
write_manifest "$TEST_ROOT/nxport-a.json" "$RUNTIME_A" 'V4 Rollback A'
write_manifest "$TEST_ROOT/nxport-b.json" "$RUNTIME_B" 'V4 Rollback B'
generate_fixture "$TEST_ROOT/nxport-a.json" "$GEN_A" "$RUNTIME_A" ||
  fail 'generator refused generation A'
generate_fixture "$TEST_ROOT/nxport-b.json" "$GEN_B" "$RUNTIME_B" ||
  fail 'generator refused generation B'

read_generation_id() {
  local commits=("$1/$PORT_ID/.nxruntime/generations"/*/commit)
  [[ ${#commits[@]} == 1 && -f ${commits[0]} ]] ||
    fail "$1 does not contain exactly one committed generation"
  cat "${commits[0]}"
}
GA_ID=$(read_generation_id "$GEN_A")
GB_ID=$(read_generation_id "$GEN_B")
[[ $GA_ID =~ ^[0-9a-f]{64}$ && $GB_ID =~ ^[0-9a-f]{64}$ &&
   $GA_ID != "$GB_ID" ]] || fail 'A/B identities are not distinct full SHA-256 values'

install_fresh() {
  local generated=$1
  rm -rf -- "$PORT_DIR" "$LAUNCHER"
  mkdir -p "$PORT_DIR"
  cp -a "$generated/$PORT_ID/." "$PORT_DIR/"
  cp -a "$generated/$LAUNCHER_NAME" "$LAUNCHER"
}

replace_regular_atomic() {
  local source=$1 target=$2 temporary
  [[ -f $source && ! -L $source ]] ||
    fail "update source is not a real file: $source"
  temporary=$target.fixture-update.$$.$RANDOM
  rm -f -- "$temporary"
  cp -a -- "$source" "$temporary" || {
    rm -f -- "$temporary"
    return 1
  }
  mv -f -- "$temporary" "$target" || {
    rm -f -- "$temporary"
    return 1
  }
}

install_update() {
  local generated=$1 generation_id
  generation_id=$(read_generation_id "$generated")
  mkdir -p "$NXRUNTIME_DIR/generations"
  rm -rf -- "$NXRUNTIME_DIR/generations/$generation_id"
  cp -a "$generated/$PORT_ID/.nxruntime/generations/$generation_id" \
    "$NXRUNTIME_DIR/generations/"
  replace_regular_atomic "$generated/$PORT_ID/nxport.json" \
    "$PORT_DIR/nxport.json" || fail 'cannot atomically install B nxport'
  replace_regular_atomic "$generated/$PORT_ID/nxsplash-nextos" \
    "$PORT_DIR/nxsplash-nextos" || fail 'cannot atomically install B splash'
  replace_regular_atomic "$generated/$PORT_ID/rollback-loader" \
    "$PORT_DIR/rollback-loader" || fail 'cannot atomically install B runtime'
  replace_regular_atomic "$generated/$LAUNCHER_NAME" "$LAUNCHER" ||
    fail 'cannot atomically install B launcher'
}

write_state() {
  local active=$1 pending=$2 previous=$3 seq=$4 failures=$5
  local failure_generation=$6 last_health_run_id=$7
  printf '%s\n' \
    "{\"schema\":\"nxruntime-state-v2\",\"schema_version\":2,\"active\":\"$active\",\"pending\":\"$pending\",\"previous_healthy\":\"$previous\",\"activation_seq\":$seq,\"prehealth_failures\":$failures,\"failure_generation\":\"$failure_generation\",\"last_health_run_id\":\"$last_health_run_id\"}" \
    > "$STATE"
}

owner_manifest() {
  local destination=$1 relative digest
  : > "$destination"
  for relative in gamedata/sentinel.bin saves/save.dat owner-cache/index.dat \
    NEXTOSCONTROLLERS.gptk NEXTOSSETTINGS.txt; do
    [[ -f $PORT_DIR/$relative && ! -L $PORT_DIR/$relative ]] ||
      fail "owner path changed type or disappeared: $relative"
    digest=$(sha256sum "$PORT_DIR/$relative")
    digest=${digest%% *}
    printf '%s  %s\n' "$digest" "$relative" >> "$destination"
  done
}

file_sha_or_absent() {
  local path=$1 digest
  if [[ -f $path && ! -L $path ]]; then
    digest=$(sha256sum "$path")
    printf '%s\n' "${digest%% *}"
  else
    printf 'absent\n'
  fi
}

events_run_id() {
  python3 -B - "$1" <<'PY'
import json
import sys

run_ids = set()
with open(sys.argv[1], encoding="utf-8") as stream:
    for number, line in enumerate(stream, 1):
        event = json.loads(line)
        run_id = event.get("run_id")
        if not isinstance(run_id, str) or not run_id:
            raise SystemExit(f"event {number} lacks run_id")
        run_ids.add(run_id)
if len(run_ids) != 1:
    raise SystemExit(f"mixed run ids: {sorted(run_ids)}")
print(next(iter(run_ids)))
PY
}

parse_trace() {
  python3 -B - "$1" <<'PY'
import json
import sys

with open(sys.argv[1], encoding="utf-8") as stream:
    lines = [line for line in stream if line.strip()]
if len(lines) != 1:
    raise SystemExit(f"trace line count is {len(lines)}, expected 1")
record = json.loads(lines[0])
required = ("build", "mode", "pid", "ppid", "starttime", "run_id",
            "generation", "health_file", "receipt_run_id", "overlap")
if any(key not in record for key in required):
    raise SystemExit("trace is missing fields")
if record["overlap"] is not False:
    raise SystemExit("runtime overlap was observed")
print("\t".join(str(record[key]) for key in required[:-1]))
PY
}

assert_state() {
  python3 -B - "$STATE" "$1" "$2" "$3" "$4" "$5" "$6" "$7" <<'PY'
import json
import sys

path, active, pending, previous, sequence, failures, failure_generation, last_health = sys.argv[1:]
with open(path, encoding="utf-8") as stream:
    state = json.load(stream)
expected = {
    "schema": "nxruntime-state-v2",
    "schema_version": 2,
    "active": active,
    "pending": pending,
    "previous_healthy": previous,
    "activation_seq": int(sequence),
    "prehealth_failures": int(failures),
    "failure_generation": failure_generation,
    "last_health_run_id": last_health,
}
actual = {key: state.get(key) for key in expected}
if actual != expected:
    raise SystemExit(f"state mismatch: actual={actual} expected={expected}")
PY
}

assert_phase() {
  python3 -B - "$PHASE" "$1" "$2" "$3" <<'PY'
import json
import sys

path, run_id, launcher_pid, child_status = sys.argv[1:]
with open(path, encoding="utf-8") as stream:
    phase = json.load(stream)
expected_status = "ok" if int(child_status) == 0 else "failed"
expected = {
    "run_id": run_id,
    "pid": int(launcher_pid),
    "phase": "runtime",
    "boundary": "EXIT",
    "child_status": int(child_status),
    "status": expected_status,
}
actual = {key: phase.get(key) for key in expected}
if actual != expected:
    raise SystemExit(f"phase mismatch: actual={actual} expected={expected}")
PY
}

declare -A SEEN_LAUNCHER_PIDS=()
declare -A SEEN_LAUNCHER_IDENTITIES=()
declare -A SEEN_CHILD_IDENTITIES=()
declare -A SEEN_RUN_IDS=()
register_unique() {
  local table_name=$1 value=$2 description=$3
  local -n table=$table_name
  [[ -n $value && -z ${table[$value]+present} ]] ||
    fail "$description was reused: $value"
  table[$value]=1
}

assert_no_fixture_process() {
  local proc environ
  for proc in /proc/[0-9]*; do
    [[ -r $proc/environ ]] || continue
    environ=$(tr '\000' '\n' < "$proc/environ" 2>/dev/null || true)
    if grep -Fxq "NXROLLBACK_TEST_TOKEN=$FIXTURE_TOKEN" <<< "$environ"; then
      fail "fixture process survived: ${proc#/proc/}"
    fi
  done
}

ALLOW_STALE_HEALTH=
assert_hygiene() {
  local lock_dir lock_file path
  if find "$NXRUNTIME_DIR" -mindepth 1 \
      \( -name 'staging.*' -o -name '.state.json.tmp.*' -o -name '*.nxheal.*' \) \
      -print -quit 2>/dev/null | grep -q .; then
    fail 'framework staging/state/heal temporary survived an attempt'
  fi
  lock_dir=$RUNTIME_DIR/.nxbootstrap-$(id -u)
  lock_file=$lock_dir/nxport-$PORT_ID.flock
  [[ -d $lock_dir && ! -L $lock_dir && -f $lock_file && ! -L $lock_file ]] ||
    fail 'stable lock objects are absent or unsafe'
  [[ ! -e $lock_file.d && ! -L $lock_file.d ]] ||
    fail 'fallback lock directory survived while flock is available'
  exec {hygiene_lock_fd}>>"$lock_file" || fail 'cannot reopen stable lock'
  flock -n "$hygiene_lock_fd" || fail 'stable lock remained held after launcher exit'
  flock -u "$hygiene_lock_fd" || true
  exec {hygiene_lock_fd}>&-
  for path in "$lock_dir"/health-$PORT_ID-*; do
    [[ -e $path || -L $path ]] || continue
    [[ -n $ALLOW_STALE_HEALTH && $path == "$ALLOW_STALE_HEALTH" &&
       -f $path && ! -L $path ]] ||
      fail "unexpected health temporary/receipt survived: $path"
  done
  assert_no_fixture_process
}

LAUNCH_PID=
LAUNCH_STARTTIME=
LAUNCH_START_NS=
LAUNCH_DEADLINE_NS=
start_launcher() {
  local mode=$1 trace=$2 release_file=$3 late_request=$4 identity state
  env -i PATH="/usr/bin:/bin" HOME="$TEST_ROOT/home" USER=fixture \
    TMPDIR="${TMPDIR:-/tmp}" XDG_DATA_HOME="$TEST_ROOT/xdg" \
    XDG_CONFIG_HOME="$TEST_ROOT/xdg" XDG_RUNTIME_DIR="$RUNTIME_DIR" \
    NXROLLBACK_MODE="$mode" NXROLLBACK_TRACE="$trace" \
    NXROLLBACK_EXCLUSIVE_LOCK="$EXCLUSIVE_RUNTIME_LOCK" \
    NXROLLBACK_RELEASE_FILE="$release_file" \
    NXROLLBACK_LATE_REQUEST="$late_request" \
    NXROLLBACK_TEST_TOKEN="$FIXTURE_TOKEN" \
    bash "$LAUNCHER" </dev/null >/dev/null 2>&1 &
  LAUNCH_PID=$!
  identity=$(proc_state_starttime "$LAUNCH_PID") ||
    fail 'could not capture launcher PID/starttime'
  read -r state LAUNCH_STARTTIME <<< "$identity"
  [[ $state != Z && $state != X ]] || fail 'launcher died before identity capture'
  LAUNCH_START_NS=$(monotonic_ns)
  LAUNCH_DEADLINE_NS=$((LAUNCH_START_NS + 8000000000))
  track_owned_pid "$LAUNCH_PID" "$LAUNCH_STARTTIME"
}

copy_attempt_artifacts() {
  local attempt_dir=$1
  [[ -f $LOG ]] && cp -a "$LOG" "$attempt_dir/log.txt"
  [[ -f $EVENTS ]] && cp -a "$EVENTS" "$attempt_dir/events.jsonl"
  [[ -f $PHASE ]] && cp -a "$PHASE" "$attempt_dir/phase.json"
  [[ -f $PORT_DIR/log.prev.txt ]] &&
    cp -a "$PORT_DIR/log.prev.txt" "$attempt_dir/log.prev.txt"
  [[ -f $PORT_DIR/events.prev.jsonl ]] &&
    cp -a "$PORT_DIR/events.prev.jsonl" "$attempt_dir/events.prev.jsonl"
  return 0
}

write_attempt_receipt() {
  local receipt=$1 name=$2 mode=$3 expected_status=$4 expected_child=$5
  local expected_build=$6 launcher_pid=$7 launcher_start=$8 runtime_pid=$9
  shift 9
  local runtime_start=$1 runtime_run=$2 selector_run=$3 start_ns=$4 deadline_ns=$5
  local end_ns=$6 owner_before=$7 owner_after=$8 state_before=$9
  shift 9
  local state_after=$1 expected_active=$2 expected_pending=$3 expected_previous=$4
  local expected_sequence=$5 expected_failures=$6 expected_failure_generation=$7
  local expected_last_health=$8
  python3 -B - "$receipt" "$STATE" "$name" "$mode" "$expected_status" \
    "$expected_child" "$expected_build" "$launcher_pid" "$launcher_start" \
    "$runtime_pid" "$runtime_start" "$runtime_run" "$selector_run" \
    "$start_ns" "$deadline_ns" "$end_ns" "$owner_before" "$owner_after" \
    "$state_before" "$state_after" "$expected_active" "$expected_pending" \
    "$expected_previous" "$expected_sequence" "$expected_failures" \
    "$expected_failure_generation" "$expected_last_health" "$LOG" \
    "$EVENTS" "$PHASE" <<'PY'
import hashlib
import json
import os
import sys

(receipt, state_path, name, mode, launcher_status, child_status,
 expected_build, launcher_pid, launcher_start, runtime_pid, runtime_start,
 runtime_run, selector_run, start_ns, deadline_ns, end_ns, owner_before,
 owner_after, state_before, state_after, expected_active, expected_pending,
 expected_previous, expected_sequence, expected_failures,
 expected_failure_generation, expected_last_health, log_path, events_path,
 phase_path) = sys.argv[1:]

with open(state_path, encoding="utf-8") as stream:
    actual_state = json.load(stream)
expected_state = {
    "schema": "nxruntime-state-v2",
    "schema_version": 2,
    "active": expected_active,
    "pending": expected_pending,
    "previous_healthy": expected_previous,
    "activation_seq": int(expected_sequence),
    "prehealth_failures": int(expected_failures),
    "failure_generation": expected_failure_generation,
    "last_health_run_id": expected_last_health,
}
actual_projection = {key: actual_state.get(key) for key in expected_state}
if actual_projection != expected_state:
    raise SystemExit("receipt state projection does not match expectation")
if owner_before != owner_after:
    raise SystemExit("owner hashes changed")
if int(end_ns) > int(deadline_ns):
    raise SystemExit("attempt crossed its monotonic deadline")

def digest(path):
    if not os.path.isfile(path) or os.path.islink(path):
        return None
    with open(path, "rb") as stream:
        return hashlib.sha256(stream.read()).hexdigest()

runtime = None
if expected_build != "NONE":
    runtime = {
        "build": expected_build,
        "pid": int(runtime_pid),
        "starttime": runtime_start,
        "run_id": runtime_run,
        "child_status": int(child_status),
    }
record = {
    "schema": "org.nextos.nxbootstrap.v4-rollback-attempt",
    "schema_version": 1,
    "attempt": name,
    "mode": mode,
    "timing": {
        "clock": "linux-proc-uptime-boottime",
        "start_ns": int(start_ns),
        "deadline_ns": int(deadline_ns),
        "end_ns": int(end_ns),
        "timed_out": False,
    },
    "launcher": {
        "pid": int(launcher_pid),
        "starttime": launcher_start,
        "status": int(launcher_status),
        "selector_run_id": selector_run or None,
    },
    "runtime": runtime,
    "owner_state": {
        "before_sha256": owner_before,
        "after_sha256": owner_after,
        "byte_identical": True,
    },
    "framework_state": {
        "before_sha256": state_before,
        "after_sha256": state_after,
        "expected": expected_state,
        "actual": actual_projection,
    },
    "artifacts": {
        "log_sha256": digest(log_path),
        "events_sha256": digest(events_path),
        "phase_sha256": digest(phase_path),
    },
    "hygiene": {
        "lock_reopen": True,
        "staging_absent": True,
        "state_temporaries_absent": True,
        "owned_processes_absent": True,
    },
}
with open(receipt, "w", encoding="utf-8") as stream:
    json.dump(record, stream, sort_keys=True, separators=(",", ":"))
    stream.write("\n")
PY
}

LAST_RUNTIME_PID=
LAST_RUNTIME_START=
LAST_RUNTIME_RUN_ID=
LAST_HEALTH_FILE=
LAST_ATTEMPT_END_NS=
CURRENT_HEALTH_RUN_ID=
run_attempt() {
  local name=$1 mode=$2 expected_status=$3 expected_child=$4 expected_build=$5
  local expected_active=$6 expected_pending=$7 expected_previous=$8
  local expected_sequence=$9 expected_failures=${10}
  local expected_failure_generation=${11} expected_last_health=${12}
  local expected_code=${13:-} selector_code=${14:-}
  local attempt_dir trace release_file late_request owner_before owner_after
  local owner_before_sha owner_after_sha state_before_sha state_after_sha
  local status end_ns finish_count current_run selector_run=''
  local trace_build trace_mode runtime_pid runtime_ppid runtime_start runtime_run
  local runtime_generation health_file receipt_run_id expected_generation

  attempt_dir=$ATTEMPTS/$name
  CURRENT_ATTEMPT_DIR=$attempt_dir
  mkdir -p "$attempt_dir"
  trace=$attempt_dir/runtime-trace.jsonl
  release_file=$attempt_dir/release
  late_request=$attempt_dir/late-request
  owner_before=$attempt_dir/owner.before.sha256
  owner_after=$attempt_dir/owner.after.sha256
  owner_manifest "$owner_before"
  owner_before_sha=$(file_sha_or_absent "$owner_before")
  state_before_sha=$(file_sha_or_absent "$STATE")
  : > "$MARKERS/pm-finish"

  start_launcher "$mode" "$trace" "$release_file" "$late_request"
  register_unique SEEN_LAUNCHER_PIDS "$LAUNCH_PID" 'launcher PID'
  register_unique SEEN_LAUNCHER_IDENTITIES "$LAUNCH_PID:$LAUNCH_STARTTIME" \
    'launcher PID/starttime'
  wait_exact_deadline "$LAUNCH_PID" "$LAUNCH_STARTTIME" "$LAUNCH_DEADLINE_NS"
  status=$WAIT_STATUS
  untrack_owned_pid "$LAUNCH_PID"
  [[ $WAIT_TIMED_OUT == 0 ]] || fail "$name crossed its monotonic deadline"
  [[ $status == "$expected_status" ]] ||
    fail "$name launcher status=$status expected=$expected_status"
  end_ns=$(monotonic_ns)
  LAST_ATTEMPT_END_NS=$end_ns
  copy_attempt_artifacts "$attempt_dir"
  finish_count=$(wc -l < "$MARKERS/pm-finish")
  [[ $finish_count == 1 ]] || fail "$name pm_finish count=$finish_count expected=1"

  runtime_pid=0
  runtime_start=none
  runtime_run=
  health_file=
  if [[ $expected_build == NONE ]]; then
    [[ ! -s $trace ]] || fail "$name unexpectedly started a runtime"
    [[ -s $EVENTS ]] || fail "$name produced no structured update receipt"
    current_run=$(events_run_id "$EVENTS") || fail "$name current events mix run ids"
    register_unique SEEN_RUN_IDS "$current_run" 'run id'
    ! grep -Fq 'PHASE runtime START' "$LOG" ||
      fail "$name crossed the runtime boundary"
  else
    [[ -s $trace ]] || fail "$name runtime trace is absent"
    IFS=$'\t' read -r trace_build trace_mode runtime_pid runtime_ppid \
      runtime_start runtime_run runtime_generation health_file receipt_run_id \
      < <(parse_trace "$trace") || fail "$name runtime trace is malformed"
    [[ $trace_build == "$expected_build" && $trace_mode == "$mode" ]] ||
      fail "$name ran build/mode $trace_build/$trace_mode"
    if [[ $expected_build == A ]]; then expected_generation=$GA_ID; else expected_generation=$GB_ID; fi
    [[ $runtime_generation == "$expected_generation" ]] ||
      fail "$name runtime generation does not match build $expected_build"
    [[ $runtime_ppid == "$LAUNCH_PID" ]] ||
      fail "$name runtime parent=$runtime_ppid launcher=$LAUNCH_PID"
    register_unique SEEN_CHILD_IDENTITIES "$runtime_pid:$runtime_start" \
      'runtime PID/starttime'
    register_unique SEEN_RUN_IDS "$runtime_run" 'run id'
    if proc_exact_alive "$runtime_pid" "$runtime_start"; then
      fail "$name runtime survived launcher wait"
    fi
    current_run=$(events_run_id "$EVENTS") || fail "$name current events mix run ids"
    [[ $current_run == "$runtime_run" ]] ||
      fail "$name events run_id differs from runtime run_id"
    assert_phase "$runtime_run" "$LAUNCH_PID" "$expected_child" ||
      fail "$name phase receipt lost child status/PID/run"
    grep -Fq "PHASE runtime EXIT status=$expected_child" "$LOG" ||
      fail "$name log lacks true child status $expected_child"
    if [[ $mode == RECYCLED_PID_RECEIPT ]]; then
      [[ $receipt_run_id == "$PORT_ID-$LAUNCH_PID-recycled-pid-stale" &&
         $receipt_run_id != "$runtime_run" ]] ||
        fail 'recycled-PID receipt did not retain PID while changing run identity'
    fi
  fi

  if [[ -n $selector_code ]]; then
    [[ -s $PORT_DIR/events.prev.jsonl && -s $PORT_DIR/log.prev.txt ]] ||
      fail "$name selector receipts were not rotated across generation restart"
    grep -Fq "\"code\":\"$selector_code\"" "$PORT_DIR/events.prev.jsonl" ||
      fail "$name selector event $selector_code is absent"
    grep -Fq "UPDATE $selector_code:" "$PORT_DIR/log.prev.txt" ||
      fail "$name selector log $selector_code is absent"
    selector_run=$(events_run_id "$PORT_DIR/events.prev.jsonl") ||
      fail "$name selector events mix run ids"
    [[ $selector_run != "$runtime_run" ]] ||
      fail "$name reused selector run id after exec restart"
    register_unique SEEN_RUN_IDS "$selector_run" 'selector run id'
  fi
  if [[ -n $expected_code ]]; then
    grep -Fq "\"code\":\"$expected_code\"" "$EVENTS" ||
      fail "$name structured event $expected_code is absent"
    grep -Fq "UPDATE $expected_code:" "$LOG" ||
      fail "$name human receipt $expected_code is absent"
  fi

  if [[ $expected_last_health == RUNTIME_RUN ]]; then
    [[ -n $runtime_run ]] ||
      fail "$name expected a new health run without starting a runtime"
    expected_last_health=$runtime_run
    CURRENT_HEALTH_RUN_ID=$runtime_run
  fi
  assert_state "$expected_active" "$expected_pending" "$expected_previous" \
    "$expected_sequence" "$expected_failures" "$expected_failure_generation" \
    "$expected_last_health" ||
    fail "$name state transition is wrong"
  owner_manifest "$owner_after"
  cmp -s "$owner_before" "$owner_after" || fail "$name changed owner bytes"
  owner_after_sha=$(file_sha_or_absent "$owner_after")
  state_after_sha=$(file_sha_or_absent "$STATE")
  assert_hygiene
  end_ns=$(monotonic_ns)
  LAST_ATTEMPT_END_NS=$end_ns
  write_attempt_receipt "$attempt_dir/receipt.json" "$name" "$mode" \
    "$expected_status" "$expected_child" "$expected_build" "$LAUNCH_PID" \
    "$LAUNCH_STARTTIME" "$runtime_pid" "$runtime_start" "$runtime_run" \
    "$selector_run" "$LAUNCH_START_NS" "$LAUNCH_DEADLINE_NS" "$end_ns" \
    "$owner_before_sha" "$owner_after_sha" "$state_before_sha" \
    "$state_after_sha" "$expected_active" "$expected_pending" \
    "$expected_previous" "$expected_sequence" "$expected_failures" \
    "$expected_failure_generation" "$expected_last_health" ||
    fail "$name structured attempt receipt is invalid"
  python3 -m json.tool "$attempt_dir/receipt.json" >/dev/null ||
    fail "$name receipt is not JSON"

  LAST_RUNTIME_PID=$runtime_pid
  LAST_RUNTIME_START=$runtime_start
  LAST_RUNTIME_RUN_ID=$runtime_run
  LAST_HEALTH_FILE=$health_file
  CURRENT_ATTEMPT_DIR=
}

# PID-reuse guard for the test runner itself: a matching numeric PID with the
# wrong starttime must never be signalled. Then the exact identity is cleaned.
sleep 30 &
recycle_probe_pid=$!
recycle_identity=$(proc_state_starttime "$recycle_probe_pid") ||
  fail 'cannot capture recycled-PID guard process'
read -r _ recycle_probe_start <<< "$recycle_identity"
track_owned_pid "$recycle_probe_pid" "$recycle_probe_start"
wrong_start=$((recycle_probe_start + 1))
if terminate_exact "$recycle_probe_pid" "$wrong_start"; then
  fail 'cleanup accepted a recycled PID with the wrong starttime'
fi
proc_exact_alive "$recycle_probe_pid" "$recycle_probe_start" ||
  fail 'wrong-starttime cleanup touched the unrelated survivor'
terminate_exact "$recycle_probe_pid" "$recycle_probe_start" ||
  fail 'exact cleanup refused its owned process'
set +e
wait "$recycle_probe_pid"
recycle_status=$?
set -e
untrack_owned_pid "$recycle_probe_pid"
[[ $recycle_status == 143 ]] ||
  fail "exact recycled-PID guard cleanup status=$recycle_status expected=143"
python3 -B - "$ATTEMPTS/recycled-pid-cleanup.json" "$recycle_probe_pid" \
  "$recycle_probe_start" "$wrong_start" <<'PY'
import json
import sys

path, pid, actual, refused = sys.argv[1:]
with open(path, "w", encoding="utf-8") as stream:
    json.dump({
        "schema": "org.nextos.nxbootstrap.v4-rollback-pid-guard",
        "schema_version": 1,
        "pid": int(pid),
        "actual_starttime": actual,
        "refused_recycled_starttime": refused,
        "unrelated_survived": True,
        "exact_cleanup": True,
    }, stream, sort_keys=True, separators=(",", ":"))
    stream.write("\n")
PY

# Install and prove A healthy before introducing a pending B.
install_fresh "$GEN_A"
mkdir -p "$PORT_DIR/gamedata" "$PORT_DIR/saves" "$PORT_DIR/owner-cache"
printf '\000owner-gamedata\377\n' > "$PORT_DIR/gamedata/sentinel.bin"
printf 'slot=7\nprogress=42\n' > "$PORT_DIR/saves/save.dat"
printf 'cache-owner-record\n' > "$PORT_DIR/owner-cache/index.dat"
printf 'format = NEXTOS_CONTROLLERS/1\n[gameplay]\na = "A"\n' \
  > "$PORT_DIR/NEXTOSCONTROLLERS.gptk"
printf '# NEXTOS_SETTINGS/1\nlanguage=pt_BR\nquality=medium\n' \
  > "$PORT_DIR/NEXTOSSETTINGS.txt"
run_attempt a-healthy SUCCESS 0 0 A "$GA_ID" null null 1 0 null \
  RUNTIME_RUN NXU0006

# Actual cross-generation concurrent launch: A remains alive across an atomic
# update to B, then B's launcher must fail before creating its child. Assertions
# use the two trace files, never the rotating shared log that the rejected
# launcher is allowed to open.
CONCURRENT_DIR=$ATTEMPTS/concurrent-singleton
CURRENT_ATTEMPT_DIR=$CONCURRENT_DIR
mkdir -p "$CONCURRENT_DIR"
owner_manifest "$CONCURRENT_DIR/owner.before.sha256"
concurrent_owner_before=$(file_sha_or_absent "$CONCURRENT_DIR/owner.before.sha256")
concurrent_state_before=$(file_sha_or_absent "$STATE")
: > "$MARKERS/pm-finish"
primary_trace=$CONCURRENT_DIR/primary.trace.jsonl
secondary_trace=$CONCURRENT_DIR/secondary.trace.jsonl
primary_release=$CONCURRENT_DIR/release-primary
start_launcher HOLD "$primary_trace" "$primary_release" "$CONCURRENT_DIR/no-late-primary"
primary_pid=$LAUNCH_PID
primary_start=$LAUNCH_STARTTIME
primary_start_ns=$LAUNCH_START_NS
primary_deadline=$LAUNCH_DEADLINE_NS
register_unique SEEN_LAUNCHER_PIDS "$primary_pid" 'launcher PID'
register_unique SEEN_LAUNCHER_IDENTITIES "$primary_pid:$primary_start" \
  'launcher PID/starttime'
trace_deadline=$(( $(monotonic_ns) + 3000000000 ))
while [[ ! -s $primary_trace ]]; do
  proc_exact_alive "$primary_pid" "$primary_start" ||
    fail 'primary concurrent launcher died before runtime trace'
  (( $(monotonic_ns) < trace_deadline )) ||
    fail 'primary concurrent runtime did not start before deadline'
  sleep 0.02
done
IFS=$'\t' read -r primary_build primary_mode primary_child primary_child_ppid primary_child_start \
  primary_run _ _ _ < <(parse_trace "$primary_trace") ||
  fail 'primary concurrent trace is malformed'
[[ $primary_build == A && $primary_mode == HOLD ]] ||
  fail 'primary concurrent runtime is not generation A in HOLD mode'
[[ $primary_child_ppid == "$primary_pid" ]] || fail 'primary child parent mismatch'
register_unique SEEN_CHILD_IDENTITIES "$primary_child:$primary_child_start" \
  'runtime PID/starttime'
register_unique SEEN_RUN_IDS "$primary_run" 'run id'

# Publish B with atomic top-level replacements while A still owns the stable
# per-port lock. This is the old-inode/deleted-path field shape: the next
# launcher carries B, but it must not start B beside the already-running A.
install_update "$GEN_B"
write_state "$GA_ID" "$GB_ID" "$GA_ID" 2 0 "$GB_ID" \
  "$CURRENT_HEALTH_RUN_ID"
for installed_member in nxport.json nxsplash-nextos rollback-loader; do
  cmp -s "$GEN_B/$PORT_ID/$installed_member" \
    "$PORT_DIR/$installed_member" ||
    fail "concurrent top-level member is not generation B: $installed_member"
done
cmp -s "$GEN_B/$LAUNCHER_NAME" "$LAUNCHER" ||
  fail 'concurrent installed launcher is not byte-exact generation B'
grep -Fq "NXBOOTSTRAP_GENERATION_ID=$GB_ID" "$LAUNCHER" ||
  fail 'concurrent secondary launcher does not carry generation B'
proc_exact_alive "$primary_child" "$primary_child_start" ||
  fail 'atomic B update disturbed the live generation A runtime'

start_launcher SHOULD_NOT_RUN "$secondary_trace" "$CONCURRENT_DIR/no-release-secondary" \
  "$CONCURRENT_DIR/no-late-secondary"
secondary_pid=$LAUNCH_PID
secondary_start=$LAUNCH_STARTTIME
secondary_deadline=$LAUNCH_DEADLINE_NS
register_unique SEEN_LAUNCHER_PIDS "$secondary_pid" 'launcher PID'
register_unique SEEN_LAUNCHER_IDENTITIES "$secondary_pid:$secondary_start" \
  'launcher PID/starttime'
wait_exact_deadline "$secondary_pid" "$secondary_start" "$secondary_deadline"
secondary_status=$WAIT_STATUS
untrack_owned_pid "$secondary_pid"
[[ $WAIT_TIMED_OUT == 0 && $secondary_status == 1 ]] ||
  fail "concurrent second launcher status=$secondary_status timeout=$WAIT_TIMED_OUT"
[[ ! -s $secondary_trace ]] || fail 'concurrent second launcher started a runtime'
proc_exact_alive "$primary_pid" "$primary_start" ||
  fail 'rejected concurrent launcher killed/replaced the primary launcher'
proc_exact_alive "$primary_child" "$primary_child_start" ||
  fail 'rejected concurrent launcher killed/replaced the primary runtime'
cp -a "$EVENTS" "$CONCURRENT_DIR/secondary.events.jsonl"
secondary_run=$(events_run_id "$CONCURRENT_DIR/secondary.events.jsonl") ||
  fail 'rejected concurrent launcher emitted mixed run ids'
register_unique SEEN_RUN_IDS "$secondary_run" 'run id'
printf 'release\n' > "$primary_release"
wait_exact_deadline "$primary_pid" "$primary_start" "$primary_deadline"
primary_status=$WAIT_STATUS
untrack_owned_pid "$primary_pid"
[[ $WAIT_TIMED_OUT == 0 && $primary_status == 0 ]] ||
  fail "primary concurrent launcher status=$primary_status timeout=$WAIT_TIMED_OUT"
if proc_exact_alive "$primary_child" "$primary_child_start"; then
  fail 'primary concurrent runtime survived release'
fi
[[ $(wc -l < "$MARKERS/pm-finish") == 2 ]] ||
  fail 'concurrent pair did not finalize PortMaster exactly once each'
CURRENT_HEALTH_RUN_ID=$primary_run
assert_state "$GA_ID" "$GB_ID" "$GA_ID" 2 0 null \
  "$CURRENT_HEALTH_RUN_ID" || fail 'cross-generation concurrency state is wrong'
owner_manifest "$CONCURRENT_DIR/owner.after.sha256"
cmp -s "$CONCURRENT_DIR/owner.before.sha256" \
  "$CONCURRENT_DIR/owner.after.sha256" || fail 'concurrent pair changed owner data'
concurrent_owner_after=$(file_sha_or_absent "$CONCURRENT_DIR/owner.after.sha256")
concurrent_state_after=$(file_sha_or_absent "$STATE")
assert_hygiene
concurrent_end=$(monotonic_ns)
python3 -B - "$CONCURRENT_DIR/receipt.json" "$STATE" "$primary_pid" "$primary_start" \
  "$primary_child" "$primary_child_start" "$primary_run" "$primary_status" \
  "$secondary_pid" "$secondary_start" "$secondary_run" "$secondary_status" \
  "$primary_start_ns" "$primary_deadline" "$concurrent_end" \
  "$concurrent_owner_before" "$concurrent_owner_after" \
  "$concurrent_state_before" "$concurrent_state_after" "$GA_ID" "$GB_ID" \
  "$CURRENT_HEALTH_RUN_ID" <<'PY'
import json
import sys

(path, state_path, primary_pid, primary_start, child_pid, child_start, primary_run,
 primary_status, secondary_pid, secondary_start, secondary_run,
 secondary_status, start_ns, deadline_ns, end_ns, owner_before,
 owner_after, state_before, state_after, generation_a, generation_b,
 last_health_run) = sys.argv[1:]
expected_state = {
    "schema": "nxruntime-state-v2",
    "schema_version": 2,
    "active": generation_a,
    "pending": generation_b,
    "previous_healthy": generation_a,
    "activation_seq": 2,
    "prehealth_failures": 0,
    "failure_generation": "null",
    "last_health_run_id": last_health_run,
}
with open(state_path, encoding="utf-8") as stream:
    actual_state = json.load(stream)
actual_projection = {key: actual_state.get(key) for key in expected_state}
if actual_projection != expected_state:
    raise SystemExit("concurrency state projection does not match expectation")
record = {
    "schema": "org.nextos.nxbootstrap.v4-rollback-concurrency",
    "schema_version": 1,
    "timing": {"clock": "linux-proc-uptime-boottime", "start_ns": int(start_ns),
               "deadline_ns": int(deadline_ns), "end_ns": int(end_ns),
               "timed_out": False},
    "primary": {"launcher_pid": int(primary_pid),
                "launcher_starttime": primary_start,
                "runtime_pid": int(child_pid), "runtime_starttime": child_start,
                "run_id": primary_run, "status": int(primary_status),
                "generation": generation_a},
    "rejected": {"launcher_pid": int(secondary_pid),
                 "launcher_starttime": secondary_start,
                 "run_id": secondary_run, "status": int(secondary_status),
                 "candidate_generation": generation_b,
                 "runtime_started": False},
    "primary_alive_after_rejection": True,
    "runtime_overlap": False,
    "owner_before_sha256": owner_before,
    "owner_after_sha256": owner_after,
    "framework_state": {"before_sha256": state_before,
                        "after_sha256": state_after,
                        "expected": expected_state,
                        "actual": actual_projection},
}
if owner_before != owner_after or int(end_ns) > int(deadline_ns):
    raise SystemExit("invalid concurrency receipt")
with open(path, "w", encoding="utf-8") as stream:
    json.dump(record, stream, sort_keys=True, separators=(",", ":"))
    stream.write("\n")
PY
CURRENT_ATTEMPT_DIR=

# B is complete and pending. Three distinct real processes die before health;
# their shell-visible statuses are asserted exactly. The fourth opening must
# select A before B can start.
run_attempt b-sigabrt ABRT 134 134 B "$GA_ID" "$GB_ID" "$GA_ID" \
  2 1 "$GB_ID" "$CURRENT_HEALTH_RUN_ID" NXU0005
run_attempt b-sigterm TERM 143 143 B "$GA_ID" "$GB_ID" "$GA_ID" \
  2 2 "$GB_ID" "$CURRENT_HEALTH_RUN_ID" NXU0005
run_attempt b-exit42 EXIT 42 42 B "$GA_ID" "$GB_ID" "$GA_ID" \
  2 3 "$GB_ID" "$CURRENT_HEALTH_RUN_ID" NXU0005
run_attempt rollback-to-a SUCCESS 0 0 A "$GA_ID" null "$GA_ID" \
  2 0 null RUNTIME_RUN '' NXU0004

# Invalid/stale receipts: exit 0, a matching numeric launcher PID with stale
# run entropy, and a receipt published only after the launcher is dead never
# promote B. The gate publishes the late receipt only after both exact launcher
# and child identities have ended, so no helper remains alive while an attempt
# receipt claims complete process hygiene.
install_update "$GEN_B"
write_state "$GA_ID" "$GB_ID" "$GA_ID" 3 0 "$GB_ID" \
  "$CURRENT_HEALTH_RUN_ID"
run_attempt stale-other-run STALE_RECEIPT 0 0 B "$GA_ID" "$GB_ID" \
  "$GA_ID" 3 1 "$GB_ID" "$CURRENT_HEALTH_RUN_ID" NXU0005
run_attempt recycled-pid-receipt RECYCLED_PID_RECEIPT 0 0 B "$GA_ID" \
  "$GB_ID" "$GA_ID" 3 2 "$GB_ID" "$CURRENT_HEALTH_RUN_ID" NXU0005

LATE_DIR=$ATTEMPTS/late-after-death
LATE_REQUEST=$LATE_DIR/late-request
LATE_DONE=$LATE_DIR/writer-done.json
mkdir -p "$LATE_DIR"
run_attempt late-after-death LATE_RECEIPT 42 42 B "$GA_ID" "$GB_ID" \
  "$GA_ID" 3 3 "$GB_ID" "$CURRENT_HEALTH_RUN_ID" NXU0005
[[ $LAST_RUNTIME_RUN_ID != '' && -n $LAST_HEALTH_FILE && -f $LATE_REQUEST ]] ||
  fail 'late receipt request did not retain its exact run/path'
mapfile -t request_lines < "$LATE_REQUEST"
[[ ${#request_lines[@]} == 4 ]] || fail 'late receipt request is malformed'
late_path=${request_lines[0]}
late_json=${request_lines[1]}
late_child=${request_lines[2]}
late_child_start=${request_lines[3]}
[[ $late_child == "$LAST_RUNTIME_PID" &&
   $late_child_start == "$LAST_RUNTIME_START" ]] ||
  fail 'late receipt request lost the exact child identity'
if proc_exact_alive "$LAUNCH_PID" "$LAUNCH_STARTTIME"; then
  fail 'late receipt writer observed the launcher still alive'
fi
if proc_exact_alive "$late_child" "$late_child_start"; then
  fail 'late receipt writer observed the child still alive'
fi
late_tmp=$late_path.tmp.late-writer.$$
(umask 077; set -C; printf '%s\n' "$late_json" > "$late_tmp") ||
  fail 'cannot create late receipt temporary'
mv -f -- "$late_tmp" "$late_path" || fail 'cannot publish late receipt'
late_written_ns=$(monotonic_ns)
python3 -B - "$LATE_DONE" "$late_path" "$late_written_ns" <<'PY'
import json
import sys
with open(sys.argv[1], "w", encoding="utf-8") as stream:
    json.dump({"schema": "org.nextos.nxbootstrap.v4-rollback-late-writer",
               "schema_version": 1, "health_file": sys.argv[2],
               "written_monotonic_ns": int(sys.argv[3])}, stream,
              sort_keys=True, separators=(",", ":"))
    stream.write("\n")
PY
late_receipt_path=$(python3 -B - "$LATE_DONE" "$LAST_ATTEMPT_END_NS" <<'PY'
import json
import sys
with open(sys.argv[1], encoding="utf-8") as stream:
    receipt = json.load(stream)
if receipt["written_monotonic_ns"] < int(sys.argv[2]):
    raise SystemExit("late receipt was not written after launcher completion")
print(receipt["health_file"])
PY
) || fail 'late writer receipt is not monotonic/structured'
[[ $late_receipt_path == "$LAST_HEALTH_FILE" && -f $late_receipt_path &&
   ! -L $late_receipt_path ]] || fail 'late receipt did not reach its old run path'
ALLOW_STALE_HEALTH=$late_receipt_path
run_attempt reopen-after-late SUCCESS 0 0 A "$GA_ID" null "$GA_ID" \
  3 0 null RUNTIME_RUN '' NXU0004
rm -f -- "$late_receipt_path"
ALLOW_STALE_HEALTH=
assert_hygiene

# Exhausted rollback with no usable anchor must fail before any runtime and
# must not rewrite state to manufacture health or select another generation.
install_update "$GEN_B"
write_state "$GA_ID" "$GB_ID" null 4 3 "$GB_ID" \
  "$CURRENT_HEALTH_RUN_ID"
missing_state_before=$(file_sha_or_absent "$STATE")
run_attempt missing-previous SHOULD_NOT_RUN 1 null NONE "$GA_ID" "$GB_ID" \
  null 4 3 "$GB_ID" "$CURRENT_HEALTH_RUN_ID" NXU0009
[[ $(file_sha_or_absent "$STATE") == "$missing_state_before" ]] ||
  fail 'missing previous_healthy failure rewrote state'

write_state "$GA_ID" "$GB_ID" "$GA_ID" 5 3 "$GB_ID" \
  "$CURRENT_HEALTH_RUN_ID"
GA_COMMIT=$NXRUNTIME_DIR/generations/$GA_ID/commit
cp -a "$GA_COMMIT" "$TEST_ROOT/ga-commit.saved"
rm -f -- "$GA_COMMIT"
corrupt_state_before=$(file_sha_or_absent "$STATE")
run_attempt corrupt-previous SHOULD_NOT_RUN 1 null NONE "$GA_ID" "$GB_ID" \
  "$GA_ID" 5 3 "$GB_ID" "$CURRENT_HEALTH_RUN_ID" NXU0009
[[ $(file_sha_or_absent "$STATE") == "$corrupt_state_before" ]] ||
  fail 'corrupt previous_healthy failure rewrote state'
cp -a "$TEST_ROOT/ga-commit.saved" "$GA_COMMIT"

# A valid anchor whose rollback state cannot be atomically persisted is also a
# pre-runtime refusal. A read-only bind mount is a real filesystem failure;
# chmod would be vacuous under the root-mapped namespace.
write_state "$GA_ID" "$GB_ID" "$GA_ID" 6 3 "$GB_ID" \
  "$CURRENT_HEALTH_RUN_ID"
persist_state_before=$(file_sha_or_absent "$STATE")
mount --bind "$NXRUNTIME_DIR" "$NXRUNTIME_DIR" || fail 'cannot bind rollback store'
mount -o remount,bind,ro "$NXRUNTIME_DIR" || fail 'cannot make rollback store read-only'
ROLLBACK_STORE_MOUNTED=1
run_attempt rollback-persist-failure SHOULD_NOT_RUN 1 null NONE "$GA_ID" \
  "$GB_ID" "$GA_ID" 6 3 "$GB_ID" "$CURRENT_HEALTH_RUN_ID" NXU0011
[[ $(file_sha_or_absent "$STATE") == "$persist_state_before" ]] ||
  fail 'failed rollback persistence changed state'
mount -o remount,bind,rw "$NXRUNTIME_DIR" || fail 'cannot restore rollback store rw'
umount "$NXRUNTIME_DIR" || fail 'cannot unmount rollback store bind'
ROLLBACK_STORE_MOUNTED=0
assert_hygiene

receipt_count=$(find "$ATTEMPTS" -name 'receipt.json' -type f | wc -l)
[[ $receipt_count == 13 ]] || fail "attempt receipt count=$receipt_count expected=13"
for receipt in "$ATTEMPTS"/*/receipt.json; do
  python3 -m json.tool "$receipt" >/dev/null || fail "invalid receipt $receipt"
done

printf 'nxbootstrap v4 rollback real crash gate passed: attempts=%s real_crashes=3 concurrency=1 stale_receipts=3 rollback=2 negatives=3 owner_hashes=preserved deadlines=linux-proc-uptime-boottime cleanup=pid-starttime\n' \
  "$receipt_count"
