#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-only
# LEGACY 0.5.1 COVERAGE ONLY. This exercises the retired nxbootstrap-0.5.1.sh
# bash library, which no generated port ships anymore. It is intentionally NOT
# part of isolated-suite.sh; the current launcher's behavioral coverage lives
# in test-launcher-behavior.sh. Kept while the retired library remains in-tree
# as contract evidence (portmaster contract still audits its source).
set -euo pipefail

PROJECT_ROOT=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd -P)
TEST_DIR=$PROJECT_ROOT/tests
# shellcheck source=private-pid-namespace.sh
source "$TEST_DIR/private-pid-namespace.sh"
nxbootstrap_require_private_pid_namespace || exit $?
TEST_ROOT=$(mktemp -d "${TMPDIR:-/tmp}/nxbootstrap-test.XXXXXX")
GAME_DIR=$TEST_ROOT/ports/synthetic
PM_DIR=$TEST_ROOT/PortMaster
RESULT=$TEST_ROOT/result.txt

cleanup() {
  case $TEST_ROOT in
    "${TMPDIR:-/tmp}"/nxbootstrap-test.*) rm -rf -- "$TEST_ROOT" ;;
  esac
}
trap cleanup EXIT INT TERM

fail() {
  printf 'nxbootstrap test failed: %s\n' "$*" >&2
  exit 1
}

top_level_version=$(
  NXBOOTSTRAP_VERSION=ambient-value \
    bash -c 'source "$1"; printf "%s" "$NXBOOTSTRAP_VERSION"' \
      _ "$PROJECT_ROOT/nxbootstrap.sh"
)
[[ $top_level_version == 0.5.1 ]] ||
  fail 'sourcing did not publish nxbootstrap version 0.5.1'

# Reloading after an older library was sourced must replace its functions. The
# published 0.5.0 assigned its version before the idempotence guard and could
# silently retain the old nxbootstrap_main body.
reload_result=$(bash -c '
  NXBOOTSTRAP_LIBRARY_LOADED=1
  NXBOOTSTRAP_VERSION=0.4.0
  NXBOOTSTRAP_LIBRARY_GENERATION=nxbootstrap-library-v4
  nxbootstrap_main() { printf "stale-main\n"; }
  stale=$(declare -f nxbootstrap_main)
  source "$1"
  current=$(declare -f nxbootstrap_main)
  [[ $NXBOOTSTRAP_VERSION == 0.5.1 ]]
  [[ $NXBOOTSTRAP_LIBRARY_GENERATION == nxbootstrap-library-v501 ]]
  [[ $current != "$stale" ]]
  source "$1"
  [[ $(declare -f nxbootstrap_main) == "$current" ]]
  printf "reload-ok\n"
' _ "$PROJECT_ROOT/nxbootstrap.sh")
[[ $reload_result == reload-ok ]] ||
  fail '0.5.1 did not replace a previously loaded 0.4.x function body'

mkdir -p "$GAME_DIR/libs" "$GAME_DIR/nxextract" "$PM_DIR/libs" \
  "$PM_DIR/libs.armhf" \
  "$TEST_ROOT/locks" "$TEST_ROOT/firmware-libs"

# Runtime fixtures are generated by the test because their paths are unique.
printf '%s\n' \
  '#!/usr/bin/env bash' \
  'printf "argc=%s\\n" "$#" > "$NXBOOTSTRAP_TEST_RESULT"' \
  'index=0' \
  'for argument in "$@"; do printf "arg%s=%s\\n" "$index" "$argument" >> "$NXBOOTSTRAP_TEST_RESULT"; index=$((index + 1)); done' \
  'printf "home=%s\\nmap=%s\\nport=%s\\ncapabilities=%s\\nquirks=%s\\nreport=%s\\n" "$HOME" "${SDL_GAMECONTROLLERCONFIG:-}" "${NXCOMPAT_PORT_ID:-}" "${NXCOMPAT_REQUIRED_CAPABILITIES:-}" "${NXCOMPAT_ENABLED_QUIRKS:-}" "${NXCOMPAT_RUNTIME_REPORT:-}" >> "$NXBOOTSTRAP_TEST_RESULT"' \
  'exit "${NXBOOTSTRAP_TEST_EXIT:-0}"' \
  > "$GAME_DIR/fake-loader"
chmod 0755 "$GAME_DIR/fake-loader"

printf '%s\n' \
  'printf "%s\n" "${LD_LIBRARY_PATH:-}" > "$NXBOOTSTRAP_TEST_CONTROL_LD"' \
  'get_controls() { sdl_controllerconfig="fixture-controller-map"; }' \
  'pm_platform_helper() { printf "%s\\n" "$1" > "$NXBOOTSTRAP_TEST_PM_HELPER"; printf "helper\\n" >> "$NXBOOTSTRAP_TEST_ORDER"; printf "helper_ld=%s\\n" "${LD_LIBRARY_PATH:-}" >> "$NXBOOTSTRAP_TEST_ORDER"; }' \
  'pm_finish() { printf "finished\\n" >> "$NXBOOTSTRAP_TEST_PM_FINISH"; }' \
  'trap '\''printf "foreign-exit\\n" >> "$NXBOOTSTRAP_TEST_FOREIGN_EXIT"'\'' EXIT' \
  'CFW_NAME=fixture' \
  > "$PM_DIR/control.txt"

printf '%s\n' \
  '#!/usr/bin/env bash' \
  'set -e' \
  'printf "extractor\\n" >> "$NXBOOTSTRAP_TEST_ORDER"' \
  'printf "extracted\\n" > "$NXEXTRACT_GAME_DIR/payload.bin"' \
  > "$GAME_DIR/nxextract/run-extractor.sh"
chmod 0644 "$GAME_DIR/nxextract/run-extractor.sh"
printf '#!/usr/bin/env python3\n' > "$GAME_DIR/nxextract/nxextract.py"
printf '#!/usr/bin/env bash\n' > "$GAME_DIR/nxextract/nxextract-runtime-env.sh"
printf '{"format_version":1}\n' > "$GAME_DIR/extractor.json"
printf '%s\n' \
  '#!/usr/bin/env bash' \
  'printf "prepare\n" >> "$NXBOOTSTRAP_TEST_ORDER"' \
  > "$GAME_DIR/prepare.sh"
chmod 0644 "$GAME_DIR/prepare.sh"

run_fixture() {
  local expected_status=$1
  shift
  set +e
  NXBOOTSTRAP_TEST_RESULT=$RESULT \
  NXBOOTSTRAP_TEST_EXIT=$expected_status \
  NXBOOTSTRAP_TEST_PM_HELPER=$TEST_ROOT/helper.txt \
  NXBOOTSTRAP_TEST_PM_FINISH=$TEST_ROOT/finish.txt \
  NXBOOTSTRAP_TEST_FOREIGN_EXIT=$TEST_ROOT/foreign-exit.txt \
  NXBOOTSTRAP_TEST_ORDER=$TEST_ROOT/order.txt \
  NXBOOTSTRAP_TEST_CONTROL_LD=$TEST_ROOT/control-ld.txt \
  NXBOOTSTRAP_PORTMASTER_ROOTS=$PM_DIR \
  NXBOOTSTRAP_LOCK_ROOT=$TEST_ROOT/locks \
  NXBOOTSTRAP_TEST_NO_TTY=1 \
  NXPORT_ID=synthetic \
  NXPORT_TITLE=Synthetic \
  NXPORT_SCHEMA_VERSION=2 \
  NXPORT_GAME_DIR=$GAME_DIR \
  NXPORT_ARCH=x86_64 \
  NXPORT_EXECUTABLE=fake-loader \
  NXPORT_ARGUMENT_MODE=game-dir-and-passthrough \
  NXPORT_HOME_MODE=port \
  NXPORT_NXEXTRACT=yes \
  NXPORT_NXEXTRACT_VERSION=1.2.7 \
  NXPORT_REQUIRED_FILES=$'payload.bin\nfake-loader' \
  NXPORT_PRIVATE_LIBRARY_PATHS=libs \
  NXPORT_PREPARE_SCRIPT=prepare.sh \
  NXPORT_REQUIRED_CAPABILITIES=$'host.portmaster\ngraphics.gles2' \
  NXPORT_ENABLED_QUIRKS=adapter.synthetic \
  NXPORT_RUNTIME_REPORT=log-and-logo \
  LD_LIBRARY_PATH=$GAME_DIR/libs:$TEST_ROOT/firmware-libs \
    bash -c 'source "$1"; shift; nxbootstrap_main "$@"' _ \
      "$PROJECT_ROOT/nxbootstrap.sh" "$@"
  local status=$?
  set -e
  [[ $status -eq $expected_status ]] ||
    fail "launcher returned $status, expected $expected_status"
}

run_fixture 7 'argument with spaces'
[[ -s $GAME_DIR/payload.bin ]] || fail 'NXExtract phase did not run'
grep -Fx "arg0=$GAME_DIR" "$RESULT" >/dev/null ||
  fail 'game directory was not the first runtime argument'
grep -Fx 'arg1=argument with spaces' "$RESULT" >/dev/null ||
  fail 'runtime argument was not preserved'
grep -Fx "home=$GAME_DIR" "$RESULT" >/dev/null ||
  fail 'HOME is not isolated to the port'
grep -Fx 'map=fixture-controller-map' "$RESULT" >/dev/null ||
  fail 'PortMaster mapping did not reach the runtime'
grep -Fx 'port=synthetic' "$RESULT" >/dev/null ||
  fail 'nxcompat identity did not reach the embedded loader'
grep -F 'capabilities=host.portmaster' "$RESULT" >/dev/null ||
  fail 'declared capabilities did not reach the embedded loader'
grep -Fx 'quirks=adapter.synthetic' "$RESULT" >/dev/null ||
  fail 'opt-in quirk did not reach the embedded loader'
grep -Fx 'report=log-and-logo' "$RESULT" >/dev/null ||
  fail 'runtime report mode did not reach the embedded loader'
[[ $(<"$TEST_ROOT/helper.txt") == "$GAME_DIR/fake-loader" ]] ||
  fail 'pm_platform_helper did not receive the real host executable'
[[ $(grep -c '^finished$' "$TEST_ROOT/finish.txt") -eq 1 ]] ||
  fail 'pm_finish did not run exactly once'
[[ $(sed -n '1p' "$TEST_ROOT/order.txt") == helper ]] ||
  fail 'pm_platform_helper did not run before setup UI'
[[ $(sed -n '3p' "$TEST_ROOT/order.txt") == extractor ]] ||
  fail 'NXExtract did not run after the prepared host environment'
[[ $(sed -n '4p' "$TEST_ROOT/order.txt") == prepare ]] ||
  fail 'prepare phase did not run after NXExtract'
grep -F 'helper_ld=' "$TEST_ROOT/order.txt" >/dev/null ||
  fail 'host library environment was not prepared before pm_platform_helper'
case :$(<"$TEST_ROOT/control-ld.txt"): in
  *:"$GAME_DIR/libs":*)
    fail 'PortMaster control loaded with a private game library provider' ;;
  *:"$TEST_ROOT/firmware-libs":*) ;;
  *) fail 'early host sanitization discarded an inherited firmware path' ;;
esac
if find "$GAME_DIR" -maxdepth 1 -name '.nxport-*.lock*' -print -quit |
    grep -q .; then
  fail 'lock was placed on the game-data filesystem'
fi
find "$TEST_ROOT/locks" -maxdepth 2 -name 'nxport-synthetic.flock' \
  -print -quit | grep -q . || fail 'runtime-local flock was not created'
grep -F 'SDL backends remain automatic' "$GAME_DIR/debug.log" >/dev/null ||
  fail 'runtime log does not record automatic backend ownership'
grep -F "PortMaster loaded (root=$PM_DIR " "$GAME_DIR/debug.log" >/dev/null ||
  fail 'runtime log does not record the selected PortMaster root'
grep -F 'nxextract=yes@1.2.7 report=log-and-logo' \
  "$GAME_DIR/debug.log" >/dev/null ||
  fail 'runtime log does not record the declarative schema contract'
grep -F 'Synthetic | nxbootstrap 0.5.1' "$GAME_DIR/debug.log" >/dev/null ||
  fail 'nxbootstrap_main downgraded the source-level version'
grep -F 'deployment_id=unknown bootstrap_path=unknown bootstrap_sha256=unknown' \
  "$GAME_DIR/debug.log" >/dev/null ||
  fail 'runtime log omits the deployment identity fields'
python3 - "$GAME_DIR/debug.log" <<'PY'
import pathlib
import sys

text = pathlib.Path(sys.argv[1]).read_text(encoding="utf-8")
phases = (
    "runtime-log-open", "portmaster-load", "session-runtime-discovery",
    "runtime-file-validation", "elf-abi-validation", "instance-lock",
    "host-environment", "display-handoff", "owner-data-extraction",
    "prepare", "required-files", "runtime-environment", "game-launch",
    "complete",
)
positions = []
for phase in phases:
    token = "[nxbootstrap] phase=%s" % phase
    position = text.find(token)
    if position < 0:
        raise SystemExit("missing runtime phase: %s" % phase)
    positions.append(position)
if positions != sorted(positions):
    raise SystemExit("runtime phases are out of order")
PY

set +e
stale_schema_output=$(NXPORT_SCHEMA_VERSION=2 NXPORT_NXEXTRACT_VERSION=1.2.4 \
NXPORT_RUNTIME_REPORT=log-and-logo \
  bash -c 'source "$1"; nxbootstrap_validate_config' \
    _ "$PROJECT_ROOT/nxbootstrap.sh" 2>&1)
stale_schema_status=$?
device_quirk_output=$(NXPORT_SCHEMA_VERSION=2 NXPORT_NXEXTRACT_VERSION=1.2.7 \
NXPORT_RUNTIME_REPORT=log-and-logo \
NXPORT_ENABLED_QUIRKS=game.device.synthetic \
  bash -c 'source "$1"; nxbootstrap_validate_config' \
    _ "$PROJECT_ROOT/nxbootstrap.sh" 2>&1)
device_quirk_status=$?
set -e
[[ $stale_schema_status -eq 1 ]] ||
  fail 'schema v2 accepted a stale NXExtract version'
grep -F 'schema v2 requires NXExtract 1.2.7' \
  <<< "$stale_schema_output" >/dev/null ||
  fail 'stale NXExtract rejection did not identify its cause'
[[ $device_quirk_status -eq 1 ]] ||
  fail 'schema v2 accepted a device-selected quirk'
grep -F 'device-selected quirk' <<< "$device_quirk_output" >/dev/null ||
  fail 'device-selected quirk rejection did not identify its cause'

INVALID_PM=$TEST_ROOT/invalid-config-portmaster
INVALID_PM_MARKER=$TEST_ROOT/invalid-config-portmaster-ran
INVALID_LOG=$TEST_ROOT/invalid-config.log
mkdir -p "$INVALID_PM"
printf 'printf "ran\\n" > %q\n' "$INVALID_PM_MARKER" > "$INVALID_PM/control.txt"
set +e
NXBOOTSTRAP_PORTMASTER_ROOTS=$INVALID_PM \
NXPORT_LOG_FILE=$INVALID_LOG NXBOOTSTRAP_TEST_NO_TTY=1 \
NXPORT_ID='INVALID ID' NXPORT_TITLE=Invalid NXPORT_GAME_DIR=$GAME_DIR \
NXPORT_ARCH=x86_64 NXPORT_EXECUTABLE=fake-loader \
  bash -c 'source "$1"; nxbootstrap_main' _ "$PROJECT_ROOT/nxbootstrap.sh" \
  >/dev/null 2>&1
invalid_config_status=$?
set -e
[[ $invalid_config_status -eq 2 && ! -e $INVALID_LOG &&
   ! -e $INVALID_PM_MARKER ]] ||
  fail 'invalid configuration caused log or PortMaster side effects'

for malformed_case in executable required libraries prepare nxextract; do
  set +e
  case $malformed_case in
    executable)
      NXPORT_EXECUTABLE_VALUE='dir//loader'
      NXPORT_REQUIRED_VALUE=
      NXPORT_LIBRARY_VALUE=
      NXPORT_PREPARE_VALUE=
      NXPORT_EXTRACT_VALUE=no
      ;;
    required)
      NXPORT_EXECUTABLE_VALUE=fake-loader
      NXPORT_REQUIRED_VALUE=$'payload.bin\npayload.bin'
      NXPORT_LIBRARY_VALUE=
      NXPORT_PREPARE_VALUE=
      NXPORT_EXTRACT_VALUE=no
      ;;
    libraries)
      NXPORT_EXECUTABLE_VALUE=fake-loader
      NXPORT_REQUIRED_VALUE=
      NXPORT_LIBRARY_VALUE=$'libs\nlibs'
      NXPORT_PREPARE_VALUE=
      NXPORT_EXTRACT_VALUE=no
      ;;
    prepare)
      NXPORT_EXECUTABLE_VALUE=fake-loader
      NXPORT_REQUIRED_VALUE=
      NXPORT_LIBRARY_VALUE=
      NXPORT_PREPARE_VALUE=./prepare.sh
      NXPORT_EXTRACT_VALUE=no
      ;;
    nxextract)
      NXPORT_EXECUTABLE_VALUE=fake-loader
      NXPORT_REQUIRED_VALUE=
      NXPORT_LIBRARY_VALUE=
      NXPORT_PREPARE_VALUE=
      NXPORT_EXTRACT_VALUE=force
      ;;
  esac
  NXPORT_ID=malformed NXPORT_TITLE=Malformed NXPORT_GAME_DIR=$GAME_DIR \
  NXPORT_ARCH=x86_64 NXPORT_EXECUTABLE=$NXPORT_EXECUTABLE_VALUE \
  NXPORT_REQUIRED_FILES=$NXPORT_REQUIRED_VALUE \
  NXPORT_PRIVATE_LIBRARY_PATHS=$NXPORT_LIBRARY_VALUE \
  NXPORT_PREPARE_SCRIPT=$NXPORT_PREPARE_VALUE \
  NXPORT_NXEXTRACT=$NXPORT_EXTRACT_VALUE \
    bash -c 'source "$1"; nxbootstrap_validate_config' \
      _ "$PROJECT_ROOT/nxbootstrap.sh" >/dev/null 2>&1
  malformed_status=$?
  set -e
  [[ $malformed_status -ne 0 ]] ||
    fail "runtime accepted malformed config case: $malformed_case"
done

armhf_path=$(
  NXPORT_ARCH=armv7 controlfolder=$PM_DIR LD_LIBRARY_PATH= \
    bash -c 'source "$1"; nxbootstrap_build_library_path 0; printf "%s" "$LD_LIBRARY_PATH"' \
      _ "$PROJECT_ROOT/nxbootstrap.sh"
)
case :$armhf_path: in
  *:"$PM_DIR/libs.armhf":*) ;;
  *) fail 'ARMv7 runtime did not use the PortMaster libs.armhf convention' ;;
esac
armhf_firmware_path=$(
  NXPORT_ARCH=armv7 bash -c \
    'source "$1"; nxbootstrap_firmware_library_path' \
    _ "$PROJECT_ROOT/nxbootstrap.sh"
)
case :$armhf_firmware_path: in
  *:/lib32:*) ;;
  *) fail 'ARMv7 firmware path omitted the legacy /lib32 directory' ;;
esac

default_pm_roots=$(bash -c 'source "$1"; nxbootstrap_default_portmaster_roots' \
  _ "$PROJECT_ROOT/nxbootstrap.sh")
for expected_root in /PortMaster /mnt/ports/PortMaster \
  /roms/tools/PortMaster /roms2/tools/PortMaster \
  /roms/Ports/PortMaster /storage/roms/Ports/PortMaster \
  /userdata/system/.local/share/PortMaster /mnt/mmc/MUOS/PortMaster \
  /mnt/mmc/Ports/PortMaster /mnt/SDCARD/Apps/PortMaster/PortMaster \
  /mnt/sdcard/Roms/.portmaster/PortMaster \
  /mnt/sdcard/MIYOO_EX/PortMaster /mnt/sdcard/ports/PortMaster; do
  grep -Fx "$expected_root" <<< "$default_pm_roots" >/dev/null ||
    fail "PortMaster root is missing: $expected_root"
done

# A compatibility alias may source a control that publishes the real root.
# The platform mod and libraries must follow that canonical controlfolder, and
# get_controls must run only after the mod.
ALIAS_PM=$TEST_ROOT/PortMaster-alias
CANONICAL_PM=$TEST_ROOT/PortMaster-canonical
CANONICAL_ORDER=$TEST_ROOT/canonical-order.txt
mkdir -p "$ALIAS_PM" "$CANONICAL_PM/libs"
printf '%s\n' \
  'controlfolder=$NXBOOTSTRAP_TEST_CANONICAL_PM' \
  'CFW_NAME=canonical' \
  'get_controls() {' \
  '  printf "controls\\n" >> "$NXBOOTSTRAP_TEST_CANONICAL_ORDER"' \
  '  [[ ${NXBOOTSTRAP_TEST_MOD_LOADED:-0} == 1 ]] || return 23' \
  '  sdl_controllerconfig=canonical-map' \
  '}' \
  'pm_finish() { :; }' \
  > "$ALIAS_PM/control.txt"
printf '%s\n' \
  'NXBOOTSTRAP_TEST_MOD_LOADED=1' \
  'printf "mod\\n" >> "$NXBOOTSTRAP_TEST_CANONICAL_ORDER"' \
  > "$CANONICAL_PM/mod_canonical.txt"
canonical_output=$(
  NXBOOTSTRAP_PORTMASTER_ROOTS=$ALIAS_PM \
  NXBOOTSTRAP_TEST_CANONICAL_PM=$CANONICAL_PM \
  NXBOOTSTRAP_TEST_CANONICAL_ORDER=$CANONICAL_ORDER \
    bash -c \
      'source "$1"; nxbootstrap_load_portmaster; trap - EXIT INT TERM; printf "root=%s map=%s\\n" "$NXCOMPAT_PORTMASTER_DIR" "$sdl_controllerconfig"' \
      _ "$PROJECT_ROOT/nxbootstrap.sh"
)
grep -F "PortMaster loaded (root=$CANONICAL_PM " \
  <<< "$canonical_output" >/dev/null ||
  fail 'control.txt canonical controlfolder was not accepted'
grep -Fx "root=$CANONICAL_PM map=canonical-map" \
  <<< "$canonical_output" >/dev/null ||
  fail 'canonical PortMaster root or mapping was not exported'
[[ $(sed -n '1p' "$CANONICAL_ORDER") == mod &&
   $(sed -n '2p' "$CANONICAL_ORDER") == controls ]] ||
  fail 'platform mod/get_controls order is incorrect'

UNSAFE_CFW_PM=$TEST_ROOT/PortMaster-unsafe-cfw
UNSAFE_CFW_MARKER=$TEST_ROOT/unsafe-cfw-mod-ran
mkdir -p "$UNSAFE_CFW_PM"
printf '%s\n' \
  "CFW_NAME='unsafe name'" \
  'trap "printf foreign-hup >/dev/null" HUP' \
  'pm_finish() { :; }' \
  > "$UNSAFE_CFW_PM/control.txt"
printf 'printf "ran\\n" > %q\n' "$UNSAFE_CFW_MARKER" \
  > "$UNSAFE_CFW_PM/mod_unsafe name.txt"
trap_contract=$(
  NXBOOTSTRAP_PORTMASTER_ROOTS=$UNSAFE_CFW_PM \
    bash -c \
      'source "$1"; nxbootstrap_load_portmaster; trap -p HUP; trap - HUP INT TERM EXIT' \
      _ "$PROJECT_ROOT/nxbootstrap.sh"
)
[[ ! -e $UNSAFE_CFW_MARKER ]] ||
  fail 'unsafe CFW_NAME was used to select a PortMaster mod'
grep -F 'nxbootstrap_on_signal 129' <<< "$trap_contract" >/dev/null ||
  fail 'PortMaster control replaced the bootstrap HUP trap'

mkdir -p "$TEST_ROOT/inherited"
runtime_library_path=$(
  NXPORT_ID=synthetic NXPORT_TITLE=Synthetic NXPORT_GAME_DIR=$GAME_DIR \
  NXPORT_ARCH=x86_64 NXPORT_EXECUTABLE=fake-loader \
  NXPORT_EXTRA_LIBRARY_PATHS=libs controlfolder=$PM_DIR \
  NXBOOTSTRAP_INHERITED_LD_LIBRARY_PATH=$TEST_ROOT/inherited \
    bash -c \
      'source "$1"; nxbootstrap_validate_config; nxbootstrap_build_library_path 1; printf "%s" "$LD_LIBRARY_PATH"' \
      _ "$PROJECT_ROOT/nxbootstrap.sh"
)
case $runtime_library_path in
  "$GAME_DIR/libs:$PM_DIR/libs:"*) ;;
  *) fail 'runtime library providers are not private -> PortMaster -> firmware' ;;
esac
host_library_path=$(
  NXPORT_ID=synthetic NXPORT_TITLE=Synthetic NXPORT_GAME_DIR=$GAME_DIR \
  NXPORT_ARCH=x86_64 NXPORT_EXECUTABLE=fake-loader \
  NXPORT_EXTRA_LIBRARY_PATHS=libs controlfolder=$PM_DIR \
  NXBOOTSTRAP_INHERITED_LD_LIBRARY_PATH=$GAME_DIR/libs:$TEST_ROOT/inherited \
    bash -c \
      'source "$1"; nxbootstrap_validate_config; nxbootstrap_build_library_path 0; printf "%s" "$LD_LIBRARY_PATH"' \
      _ "$PROJECT_ROOT/nxbootstrap.sh"
)
case $host_library_path in "$PM_DIR/libs:"*) ;; *)
  fail 'host library providers do not start with PortMaster' ;;
esac
case :$host_library_path: in *:"$GAME_DIR/libs":*)
  fail 'host setup inherited a private game library directory' ;;
esac

mkdir -p "$GAME_DIR/badlibs"
printf 'not-an-elf\n' > "$GAME_DIR/badlibs/libEGL.so.1"
set +e
NXBOOTSTRAP_TEST_NO_TTY=1 NXPORT_ID=synthetic NXPORT_TITLE=Synthetic \
NXPORT_GAME_DIR=$GAME_DIR NXPORT_ARCH=x86_64 NXPORT_EXECUTABLE=fake-loader \
NXPORT_EXTRA_LIBRARY_PATHS=badlibs controlfolder=$PM_DIR \
  bash -c \
    'source "$1"; nxbootstrap_validate_config; nxbootstrap_build_library_path 1' \
    _ "$PROJECT_ROOT/nxbootstrap.sh" >/dev/null 2>&1
bad_graphics_provider_status=$?
set -e
[[ $bad_graphics_provider_status -eq 1 ]] ||
  fail 'private LD_LIBRARY_PATH accepted a bundled graphics provider'

mkdir -p "$GAME_DIR/badsdl"
printf 'not-an-elf\n' > "$GAME_DIR/badsdl/libSDL2-2.0.so.0"
set +e
NXBOOTSTRAP_TEST_NO_TTY=1 NXPORT_ID=synthetic NXPORT_TITLE=Synthetic \
NXPORT_GAME_DIR=$GAME_DIR NXPORT_ARCH=x86_64 NXPORT_EXECUTABLE=fake-loader \
NXPORT_PRIVATE_LIBRARY_PATHS=badsdl controlfolder=$PM_DIR \
  bash -c \
    'source "$1"; nxbootstrap_validate_config; nxbootstrap_build_library_path 1' \
    _ "$PROJECT_ROOT/nxbootstrap.sh" >/dev/null 2>&1
bad_sdl_provider_status=$?
set -e
[[ $bad_sdl_provider_status -eq 1 ]] ||
  fail 'private LD_LIBRARY_PATH accepted a bundled SDL provider'

inherited_drivers=$(
  SDL_VIDEODRIVER=firmware-video SDL_AUDIODRIVER=firmware-audio \
  NXPORT_ID=synthetic NXPORT_TITLE=Synthetic NXPORT_GAME_DIR=$GAME_DIR \
  NXPORT_ARCH=x86_64 NXPORT_EXECUTABLE=fake-loader controlfolder=$PM_DIR \
    bash -c \
      'source "$1"; nxbootstrap_log() { :; }; nxbootstrap_validate_config; nxbootstrap_capture_and_filter_inherited_libraries; nxbootstrap_build_host_environment; printf "%s|%s" "$SDL_VIDEODRIVER" "$SDL_AUDIODRIVER"' \
      _ "$PROJECT_ROOT/nxbootstrap.sh"
)
[[ $inherited_drivers == firmware-video\|firmware-audio ]] ||
  fail 'bootstrap overwrote inherited SDL video/audio drivers without a real failure'

mkdir -p "$TEST_ROOT/outside"
printf '#!/usr/bin/env bash\nexit 0\n' > "$TEST_ROOT/outside/escaped-loader"
printf '#!/usr/bin/env bash\nexit 0\n' > "$TEST_ROOT/outside/prepare.sh"
printf 'owner data\n' > "$TEST_ROOT/outside/required.bin"
chmod 0755 "$TEST_ROOT/outside/escaped-loader"
ln -s "$TEST_ROOT/outside" "$GAME_DIR/escape"
set +e
NXBOOTSTRAP_PORTMASTER_ROOTS=$TEST_ROOT/no-portmaster \
NXBOOTSTRAP_TEST_NO_TTY=1 \
NXPORT_ID=escape-bin NXPORT_TITLE=Escape NXPORT_GAME_DIR=$GAME_DIR \
NXPORT_ARCH=x86_64 NXPORT_EXECUTABLE=escape/escaped-loader NXPORT_NXEXTRACT=no \
  bash -c 'source "$1"; nxbootstrap_main' _ \
    "$PROJECT_ROOT/nxbootstrap.sh" >/dev/null 2>&1
escaped_bin_status=$?
NXBOOTSTRAP_TEST_NO_TTY=1 NXPORT_ID=escape-prepare NXPORT_TITLE=Escape \
NXPORT_GAME_DIR=$GAME_DIR NXPORT_ARCH=x86_64 NXPORT_EXECUTABLE=fake-loader \
NXPORT_PREPARE_SCRIPT=escape/prepare.sh \
  bash -c \
    'source "$1"; nxbootstrap_validate_config; nxbootstrap_run_prepare' \
    _ "$PROJECT_ROOT/nxbootstrap.sh" >/dev/null 2>&1
escaped_prepare_status=$?
NXBOOTSTRAP_TEST_NO_TTY=1 NXPORT_ID=escape-required NXPORT_TITLE=Escape \
NXPORT_GAME_DIR=$GAME_DIR NXPORT_ARCH=x86_64 NXPORT_EXECUTABLE=fake-loader \
NXPORT_REQUIRED_FILES=escape/required.bin \
  bash -c \
    'source "$1"; nxbootstrap_validate_config; nxbootstrap_check_required_files' \
    _ "$PROJECT_ROOT/nxbootstrap.sh" >/dev/null 2>&1
escaped_required_status=$?
NXBOOTSTRAP_TEST_NO_TTY=1 NXPORT_ID=escape-libs NXPORT_TITLE=Escape \
NXPORT_GAME_DIR=$GAME_DIR NXPORT_ARCH=x86_64 NXPORT_EXECUTABLE=fake-loader \
NXPORT_EXTRA_LIBRARY_PATHS=escape controlfolder=$PM_DIR \
  bash -c \
    'source "$1"; nxbootstrap_validate_config; nxbootstrap_build_library_path 1' \
    _ "$PROJECT_ROOT/nxbootstrap.sh" >/dev/null 2>&1
escaped_library_status=$?
set -e
[[ $escaped_bin_status -eq 1 && $escaped_prepare_status -eq 1 &&
   $escaped_required_status -eq 1 && $escaped_library_status -eq 1 ]] ||
  fail 'an intermediate symlink escaped the port containment boundary'

printf '#!/usr/bin/env bash\nexit 0\n' > "$TEST_ROOT/hardlink-loader-victim"
chmod 0644 "$TEST_ROOT/hardlink-loader-victim"
ln "$TEST_ROOT/hardlink-loader-victim" "$GAME_DIR/hardlink-loader"
set +e
NXPORT_ID=hardlink-bin NXPORT_TITLE=Hardlink NXPORT_GAME_DIR=$GAME_DIR \
NXPORT_ARCH=x86_64 NXPORT_EXECUTABLE=hardlink-loader \
  bash -c \
    'source "$1"; nxbootstrap_validate_config; nxbootstrap_make_executable "$NXBOOTSTRAP_BIN"' \
    _ "$PROJECT_ROOT/nxbootstrap.sh" >/dev/null 2>&1
hardlink_bin_status=$?
set -e
[[ $hardlink_bin_status -ne 0 &&
   $(stat -c '%a' "$TEST_ROOT/hardlink-loader-victim") == 644 ]] ||
  fail 'runtime chmod followed or accepted a hardlinked executable'

# `exec` without a command makes every redirection persistent in the current
# shell. Descriptor helpers must silence only their individual open operation;
# otherwise the runtime inherits /dev/null on stderr and loses all engine logs.
descriptor_report=$(NXPORT_ID=descriptor-preserve \
  NXPORT_TITLE=Descriptor NXPORT_GAME_DIR=$GAME_DIR \
  NXPORT_ARCH=x86_64 NXPORT_EXECUTABLE=fake-loader \
  bash -c '
    source "$1"
    nxbootstrap_validate_config
    before=$(readlink "/proc/$$/fd/2")
    nxbootstrap_make_executable "$NXBOOTSTRAP_BIN"
    after_executable=$(readlink "/proc/$$/fd/2")
    nxbootstrap_acquire_lock
    after_lock=$(readlink "/proc/$$/fd/2")
    nxbootstrap_release_lock
    after_release=$(readlink "/proc/$$/fd/2")
    printf "%s\n%s\n%s\n%s\n" "$before" "$after_executable" \
      "$after_lock" "$after_release"
  ' _ "$PROJECT_ROOT/nxbootstrap.sh" 2>"$TEST_ROOT/descriptor-stderr.log")
mapfile -t descriptor_targets <<< "$descriptor_report"
[[ ${#descriptor_targets[@]} -eq 4 &&
   ${descriptor_targets[0]} != /dev/null &&
   ${descriptor_targets[0]} == "${descriptor_targets[1]}" &&
   ${descriptor_targets[0]} == "${descriptor_targets[2]}" &&
   ${descriptor_targets[0]} == "${descriptor_targets[3]}" ]] ||
  fail 'descriptor helpers permanently redirected runtime stderr'

printf 'outside-log\n' > "$TEST_ROOT/outside-log"
NXPORT_ID=log-containment NXPORT_TITLE=Log NXPORT_GAME_DIR=$GAME_DIR \
NXPORT_ARCH=x86_64 NXPORT_EXECUTABLE=fake-loader \
NXPORT_LOG_FILE=$GAME_DIR/../outside-log \
  bash -c \
    'source "$1"; nxbootstrap_validate_config; nxbootstrap_open_log; printf "contained-log\n"' \
    _ "$PROJECT_ROOT/nxbootstrap.sh"
[[ $(<"$TEST_ROOT/outside-log") == outside-log ]] ||
  fail 'NXPORT_LOG_FILE escaped through a parent component'

set +e
helper_failure_output=$(NXBOOTSTRAP_TEST_NO_TTY=1 \
  bash -c \
    'source "$1"; NXBOOTSTRAP_BIN=$2; pm_platform_helper() { return 9; }; nxbootstrap_platform_prepare' \
    _ "$PROJECT_ROOT/nxbootstrap.sh" "$GAME_DIR/fake-loader" \
    2>&1)
helper_failure_status=$?
set -e
[[ $helper_failure_status -eq 0 ]] ||
  fail 'best-effort pm_platform_helper failure aborted the port'
grep -F 'pm_platform_helper returned status 9; continuing' \
  <<< "$helper_failure_output" >/dev/null ||
  fail 'best-effort pm_platform_helper failure was not logged'

set +e
required_portmaster_output=$(NXBOOTSTRAP_TEST_NO_TTY=1 \
  NXPORT_TITLE=Synthetic NXPORT_REQUIRED_CAPABILITIES=host.portmaster \
  NXBOOTSTRAP_PORTMASTER_ROOTS=$TEST_ROOT/no-portmaster \
    bash -c 'source "$1"; nxbootstrap_load_portmaster' \
      _ "$PROJECT_ROOT/nxbootstrap.sh" 2>&1)
required_portmaster_status=$?
set -e
[[ $required_portmaster_status -eq 1 ]] ||
  fail 'required host.portmaster accepted a missing PortMaster control'
grep -F 'required capability host.portmaster unavailable: PortMaster control.txt not found' \
  <<< "$required_portmaster_output" >/dev/null ||
  fail 'missing required PortMaster control did not leave a clear error'

BROKEN_PM=$TEST_ROOT/broken-portmaster
mkdir -p "$BROKEN_PM"
printf 'return 23\n' > "$BROKEN_PM/control.txt"
set +e
broken_portmaster_output=$(NXBOOTSTRAP_TEST_NO_TTY=1 \
  NXPORT_TITLE=Synthetic NXPORT_REQUIRED_CAPABILITIES=host.portmaster \
  NXBOOTSTRAP_PORTMASTER_ROOTS=$BROKEN_PM \
    bash -c 'source "$1"; nxbootstrap_load_portmaster' \
      _ "$PROJECT_ROOT/nxbootstrap.sh" 2>&1)
broken_portmaster_status=$?
set -e
[[ $broken_portmaster_status -eq 1 ]] ||
  fail 'required host.portmaster accepted a failing PortMaster control'
grep -F 'required capability host.portmaster unavailable: PortMaster control.txt failed to initialize' \
  <<< "$broken_portmaster_output" >/dev/null ||
  fail 'failing required PortMaster control did not leave a clear error'

standalone_output=$(NXBOOTSTRAP_TEST_NO_TTY=1 \
  NXPORT_REQUIRED_CAPABILITIES=graphics.gles2 \
  NXBOOTSTRAP_PORTMASTER_ROOTS=$TEST_ROOT/no-portmaster \
    bash -c 'source "$1"; nxbootstrap_load_portmaster' \
      _ "$PROJECT_ROOT/nxbootstrap.sh" 2>&1)
grep -F 'PortMaster control.txt not found; standalone mode' \
  <<< "$standalone_output" >/dev/null ||
  fail 'optional PortMaster discovery no longer permits standalone mode'

# Some released CFW modules replace pm_platform_helper with an empty function,
# bypassing the default PortMasterDialogExit call.  A live PortMaster pipe is
# sufficient authority to close that exact dialog through the firmware API;
# the bootstrap must do so before any setup UI or game can request the display.
DIALOG_PIPE=$TEST_ROOT/portmaster-dialog.pipe
mkfifo "$DIALOG_PIPE"
dialog_close_output=$(NXBOOTSTRAP_TEST_NO_TTY=1 \
  bash -c '
    source "$1"
    NXBOOTSTRAP_BIN=$2
    PM_PIPE=$3
    pm_platform_helper() { :; }
    PortMasterDialogExit() {
      printf "official-close\n"
      rm -f -- "$PM_PIPE"
    }
    nxbootstrap_platform_prepare
  ' _ "$PROJECT_ROOT/nxbootstrap.sh" "$GAME_DIR/fake-loader" "$DIALOG_PIPE" \
  2>&1)
[[ ! -e $DIALOG_PIPE ]] ||
  fail 'live PortMaster dialog survived an empty platform helper'
grep -Fx 'official-close' <<< "$dialog_close_output" >/dev/null ||
  fail 'bootstrap bypassed the official PortMaster dialog close API'
grep -F 'PortMaster dialog closed after platform helper' \
  <<< "$dialog_close_output" >/dev/null ||
  fail 'PortMaster dialog closure was not logged'

run_dialog_failure_fixture() {
  local failure_case=$1 expected_error=$2 pipe=$TEST_ROOT/dialog-$1.pipe
  local output status
  mkfifo "$pipe"
  set +e
  output=$(NXBOOTSTRAP_TEST_NO_TTY=1 NXPORT_TITLE=Synthetic \
    bash -c '
      source "$1"
      NXBOOTSTRAP_BIN=$2
      PM_PIPE=$3
      case $4 in
        missing-api) ;;
        failed-close) PortMasterDialogExit() { return 19; } ;;
        persistent-pipe) PortMasterDialogExit() { return 0; } ;;
        *) exit 99 ;;
      esac
      nxbootstrap_platform_prepare
    ' _ "$PROJECT_ROOT/nxbootstrap.sh" "$GAME_DIR/fake-loader" "$pipe" \
      "$failure_case" 2>&1)
  status=$?
  set -e
  [[ $status -eq 1 ]] ||
    fail "dialog $failure_case returned $status instead of failing closed"
  grep -F "$expected_error" <<< "$output" >/dev/null ||
    fail "dialog $failure_case did not leave its fail-closed error"
  [[ -p $pipe ]] ||
    fail "dialog $failure_case fixture unexpectedly lost its live FIFO"
  rm -f -- "$pipe"
}

run_dialog_failure_fixture missing-api \
  'PortMaster dialog handoff failed: close API unavailable while PM_PIPE is active'
run_dialog_failure_fixture failed-close \
  'PortMaster dialog handoff failed: close API returned status 19'
run_dialog_failure_fixture persistent-pipe \
  'PortMaster dialog handoff failed: PM_PIPE remained after close request'

# PM_PIPE is inherited shell state until PortMasterDialog.txt initializes it.
# Never pass an arbitrary regular file or symlink to the official close API.
run_unsafe_dialog_fixture() {
  local failure_case=$1 pipe=$2 output status sentinel=$TEST_ROOT/$1.called
  set +e
  output=$(NXBOOTSTRAP_TEST_NO_TTY=1 NXPORT_TITLE=Synthetic \
    bash -c '
      source "$1"
      NXBOOTSTRAP_BIN=$2
      PM_PIPE=$3
      NXBOOTSTRAP_TEST_CLOSE_SENTINEL=$4
      PortMasterDialogExit() {
        printf "called\n" > "$NXBOOTSTRAP_TEST_CLOSE_SENTINEL"
        return 0
      }
      nxbootstrap_platform_prepare
    ' _ "$PROJECT_ROOT/nxbootstrap.sh" "$GAME_DIR/fake-loader" "$pipe" \
      "$sentinel" 2>&1)
  status=$?
  set -e
  [[ $status -eq 1 ]] ||
    fail "unsafe dialog $failure_case returned $status instead of failing closed"
  grep -F 'PortMaster dialog handoff failed: PM_PIPE is not a live non-symlink FIFO' \
    <<< "$output" >/dev/null ||
    fail "unsafe dialog $failure_case did not report its type rejection"
  [[ ! -e $sentinel ]] ||
    fail "unsafe dialog $failure_case reached PortMasterDialogExit"
}

UNSAFE_REGULAR_PIPE=$TEST_ROOT/dialog-regular.path
printf 'not-a-fifo\n' > "$UNSAFE_REGULAR_PIPE"
run_unsafe_dialog_fixture regular-file "$UNSAFE_REGULAR_PIPE"
UNSAFE_FIFO_TARGET=$TEST_ROOT/dialog-symlink-target.pipe
UNSAFE_FIFO_LINK=$TEST_ROOT/dialog-symlink.pipe
mkfifo "$UNSAFE_FIFO_TARGET"
ln -s "$UNSAFE_FIFO_TARGET" "$UNSAFE_FIFO_LINK"
run_unsafe_dialog_fixture symlink-fifo "$UNSAFE_FIFO_LINK"

set +e
NXBOOTSTRAP_TEST_NO_TTY=1 NXPORT_TITLE=Synthetic NXPORT_ARCH=x86_64 \
NXPORT_INTERPRETER=/not/the/canonical/linker \
  bash -c 'source "$1"; nxbootstrap_check_arch' \
    _ "$PROJECT_ROOT/nxbootstrap.sh" >/dev/null 2>&1
bad_interpreter_status=$?
set -e
[[ $bad_interpreter_status -eq 1 ]] ||
  fail 'runtime accepted a non-canonical PT_INTERP contract'

python3 - "$TEST_ROOT/elf-aarch64" "$TEST_ROOT/elf-armv7" \
  "$TEST_ROOT/elf-bad-interp" <<'PY'
import struct
import sys


def ident(elf_class):
    value = bytearray(16)
    value[:7] = b"\x7fELF" + bytes((elf_class, 1, 1))
    return bytes(value)


def elf64(path, interpreter):
    payload = interpreter.encode("ascii") + b"\0"
    header = struct.pack(
        "<16sHHIQQQIHHHHHH", ident(2), 3, 183, 1, 0, 64, 0, 0,
        64, 56, 1, 0, 0, 0,
    )
    phdr = struct.pack(
        "<IIQQQQQQ", 3, 4, 120, 0, 0, len(payload), len(payload), 1,
    )
    open(path, "wb").write(header + phdr + payload)


def elf32(path, interpreter):
    payload = interpreter.encode("ascii") + b"\0"
    header = struct.pack(
        "<16sHHIIIIIHHHHHH", ident(1), 3, 40, 1, 0, 52, 0,
        0x05000400, 52, 32, 1, 0, 0, 0,
    )
    phdr = struct.pack(
        "<IIIIIIII", 3, 84, 0, 0, len(payload), len(payload), 4, 1,
    )
    open(path, "wb").write(header + phdr + payload)


elf64(sys.argv[1], "/lib/ld-linux-aarch64.so.1")
elf32(sys.argv[2], "/lib/ld-linux-armhf.so.3")
elf64(sys.argv[3], "/system/bin/linker64")
PY
bash -c \
  'source "$1"; nxbootstrap_validate_elf_contract "$2" aarch64 /lib/ld-linux-aarch64.so.1' \
  _ "$PROJECT_ROOT/nxbootstrap.sh" "$TEST_ROOT/elf-aarch64" ||
  fail 'valid AArch64 ELF/PT_INTERP contract was rejected'
bash -c \
  'source "$1"; nxbootstrap_validate_elf_contract "$2" armv7 /lib/ld-linux-armhf.so.3' \
  _ "$PROJECT_ROOT/nxbootstrap.sh" "$TEST_ROOT/elf-armv7" ||
  fail 'valid ARMv7 ELF/PT_INTERP contract was rejected'
if bash -c \
    'source "$1"; nxbootstrap_validate_elf_contract "$2" aarch64 /lib/ld-linux-aarch64.so.1' \
    _ "$PROJECT_ROOT/nxbootstrap.sh" "$TEST_ROOT/elf-bad-interp"; then
  fail 'Android PT_INTERP was accepted for a Linux AArch64 runtime'
fi
if bash -c \
    'source "$1"; nxbootstrap_validate_elf_contract "$2" armv7 /lib/ld-linux-armhf.so.3' \
    _ "$PROJECT_ROOT/nxbootstrap.sh" "$TEST_ROOT/elf-aarch64"; then
  fail 'ELF class/machine mismatch was accepted'
fi

printf 'must-not-change\n' > "$TEST_ROOT/flock-victim"
symlink_lock_base=$(
  NXBOOTSTRAP_LOCK_ROOT=$TEST_ROOT/locks NXPORT_ID=symlink-lock \
    bash -c \
      'source "$1"; nxbootstrap_prepare_lock_paths; printf "%s" "$NXBOOTSTRAP_LOCK_BASE"' \
      _ "$PROJECT_ROOT/nxbootstrap.sh"
)
ln -s "$TEST_ROOT/flock-victim" "$symlink_lock_base.flock"
set +e
NXBOOTSTRAP_LOCK_ROOT=$TEST_ROOT/locks NXPORT_ID=symlink-lock \
  bash -c \
    'source "$1"; nxbootstrap_prepare_lock_paths; nxbootstrap_try_flock' \
    _ "$PROJECT_ROOT/nxbootstrap.sh"
symlink_lock_status=$?
set -e
[[ $symlink_lock_status -ne 0 ]] || fail 'flock followed a pre-existing symlink'
[[ $(<"$TEST_ROOT/flock-victim") == must-not-change ]] ||
  fail 'flock truncated a symlink target'

printf 'hardlink-lock-victim\n' > "$TEST_ROOT/flock-hardlink-victim"
hardlink_lock_base=$(
  NXBOOTSTRAP_LOCK_ROOT=$TEST_ROOT/locks NXPORT_ID=hardlink-lock \
    bash -c \
      'source "$1"; nxbootstrap_prepare_lock_paths; printf "%s" "$NXBOOTSTRAP_LOCK_BASE"' \
      _ "$PROJECT_ROOT/nxbootstrap.sh"
)
ln "$TEST_ROOT/flock-hardlink-victim" "$hardlink_lock_base.flock"
set +e
NXBOOTSTRAP_LOCK_ROOT=$TEST_ROOT/locks NXPORT_ID=hardlink-lock \
  bash -c \
    'source "$1"; nxbootstrap_prepare_lock_paths; nxbootstrap_try_flock' \
    _ "$PROJECT_ROOT/nxbootstrap.sh"
hardlink_lock_status=$?
set -e
[[ $hardlink_lock_status -ne 0 &&
   $(<"$TEST_ROOT/flock-hardlink-victim") == hardlink-lock-victim ]] ||
  fail 'flock accepted or modified an unexpected hardlink'

set +e
NXBOOTSTRAP_LOCK_ROOT=$GAME_DIR NXPORT_ID=game-root-lock \
NXPORT_TITLE=Synthetic NXPORT_GAME_DIR=$GAME_DIR NXPORT_ARCH=x86_64 \
NXPORT_EXECUTABLE=fake-loader \
  bash -c \
    'source "$1"; nxbootstrap_validate_config; nxbootstrap_prepare_lock_paths' \
    _ "$PROJECT_ROOT/nxbootstrap.sh"
game_root_lock_status=$?
set -e
[[ $game_root_lock_status -ne 0 ]] ||
  fail 'lock root was accepted on the game-data filesystem'

mkdir -p "$TEST_ROOT/world-locks"
chmod 0777 "$TEST_ROOT/world-locks"
secure_lock_root=$(
  NXBOOTSTRAP_LOCK_ROOT=$TEST_ROOT/world-locks NXPORT_ID=private-root \
    bash -c \
      'source "$1"; nxbootstrap_prepare_lock_paths; dirname -- "$NXBOOTSTRAP_LOCK_BASE"' \
      _ "$PROJECT_ROOT/nxbootstrap.sh"
)
[[ $(stat -c '%a' "$secure_lock_root") == 700 ]] ||
  fail 'lock namespace inside a shared root is not private'

mkdir -p "$TEST_ROOT/failing-flock-bin"
printf '%s\n' '#!/usr/bin/env bash' 'exit 42' > \
  "$TEST_ROOT/failing-flock-bin/flock"
chmod 0755 "$TEST_ROOT/failing-flock-bin/flock"
no_fallback_base=$(
  NXBOOTSTRAP_LOCK_ROOT=$TEST_ROOT/locks NXPORT_ID=no-split-brain \
    bash -c \
      'source "$1"; nxbootstrap_prepare_lock_paths; printf "%s" "$NXBOOTSTRAP_LOCK_BASE"' \
      _ "$PROJECT_ROOT/nxbootstrap.sh"
)
set +e
PATH=$TEST_ROOT/failing-flock-bin:$PATH \
NXBOOTSTRAP_LOCK_ROOT=$TEST_ROOT/locks NXPORT_ID=no-split-brain \
  bash -c \
    'source "$1"; nxbootstrap_prepare_lock_paths; nxbootstrap_try_lock' \
    _ "$PROJECT_ROOT/nxbootstrap.sh"
no_fallback_status=$?
set -e
[[ $no_fallback_status -ne 0 && ! -e $no_fallback_base.lockdir ]] ||
  fail 'a flock error opened a second mkdir lock namespace'

orphan_lock_base=$(
  NXBOOTSTRAP_LOCK_ROOT=$TEST_ROOT/locks NXPORT_ID=orphan-lock \
    bash -c \
      'source "$1"; nxbootstrap_prepare_lock_paths; printf "%s" "$NXBOOTSTRAP_LOCK_BASE"' \
      _ "$PROJECT_ROOT/nxbootstrap.sh"
)
mkdir -- "$orphan_lock_base.lockdir"
set +e
NXBOOTSTRAP_TEST_FORCE_MKDIR_LOCK=1 \
NXBOOTSTRAP_LOCK_ROOT=$TEST_ROOT/locks NXPORT_ID=orphan-lock \
  bash -c \
    'source "$1"; nxbootstrap_prepare_lock_paths; nxbootstrap_try_lock' \
    _ "$PROJECT_ROOT/nxbootstrap.sh"
orphan_lock_status=$?
set -e
[[ $orphan_lock_status -ne 0 && -d $orphan_lock_base.lockdir ]] ||
  fail 'ownerless mkdir lock was not handled fail-closed'
rmdir -- "$orphan_lock_base.lockdir"

mkdir_owner_record=$(
  NXBOOTSTRAP_TEST_FORCE_MKDIR_LOCK=1 \
  NXBOOTSTRAP_LOCK_ROOT=$TEST_ROOT/locks NXPORT_ID=mkdir-owner \
    bash -c '
      source "$1"
      nxbootstrap_prepare_lock_paths
      nxbootstrap_try_lock
      owner=$(<"$NXBOOTSTRAP_LOCK_PATH/owner")
      set -- $owner
      [[ $1 == $$ && $2 == "$(nxbootstrap_process_starttime "$$")" ]]
      printf "%s\n" "$owner"
      lock_path=$NXBOOTSTRAP_LOCK_PATH
      nxbootstrap_release_lock
      [[ ! -e $lock_path ]]
    ' _ "$PROJECT_ROOT/nxbootstrap.sh"
)
case $mkdir_owner_record in
  [0-9]*' '[0-9]*) ;;
  *) fail 'mkdir lock did not record owner PID+starttime' ;;
esac

tampered_lock_base=$(
  NXBOOTSTRAP_LOCK_ROOT=$TEST_ROOT/locks NXPORT_ID=tampered-owner \
    bash -c \
      'source "$1"; nxbootstrap_prepare_lock_paths; printf "%s" "$NXBOOTSTRAP_LOCK_BASE"' \
      _ "$PROJECT_ROOT/nxbootstrap.sh"
)
NXBOOTSTRAP_TEST_FORCE_MKDIR_LOCK=1 \
NXBOOTSTRAP_LOCK_ROOT=$TEST_ROOT/locks NXPORT_ID=tampered-owner \
  bash -c '
    source "$1"
    nxbootstrap_prepare_lock_paths
    nxbootstrap_try_lock
    printf "999999 1\n" > "$NXBOOTSTRAP_LOCK_PATH/owner"
    nxbootstrap_release_lock
  ' _ "$PROJECT_ROOT/nxbootstrap.sh"
[[ -d $tampered_lock_base.lockdir ]] ||
  fail 'mkdir lock release removed a lock whose owner record changed'
rm -f -- "$tampered_lock_base.lockdir/owner"
rmdir -- "$tampered_lock_base.lockdir"

OTHER_GAME_DIR=$TEST_ROOT/roms2/ports/synthetic
mkdir -p "$OTHER_GAME_DIR"
first_lock=$(
  NXBOOTSTRAP_LOCK_ROOT=$TEST_ROOT/locks NXPORT_GAME_DIR=$GAME_DIR \
    NXPORT_ID=synthetic /usr/bin/bash -c \
      'source "$1"; nxbootstrap_prepare_lock_paths; printf "%s" "$NXBOOTSTRAP_LOCK_BASE"' \
      _ "$PROJECT_ROOT/nxbootstrap.sh"
)
second_lock=$(
  NXBOOTSTRAP_LOCK_ROOT=$TEST_ROOT/locks NXPORT_GAME_DIR=$OTHER_GAME_DIR \
    NXPORT_ID=synthetic /usr/bin/bash -c \
      'source "$1"; nxbootstrap_prepare_lock_paths; printf "%s" "$NXBOOTSTRAP_LOCK_BASE"' \
      _ "$PROJECT_ROOT/nxbootstrap.sh"
)
[[ $first_lock == "$second_lock" ]] ||
  fail 'two copies of the same port received different instance locks'

ambient_proc_root=$(
  NXBOOTSTRAP_PROC_ROOT=/untrusted/ambient/value \
    /usr/bin/bash -c 'source "$1"; printf "%s" "$NXBOOTSTRAP_PROC_ROOT"' \
      _ "$PROJECT_ROOT/nxbootstrap.sh"
)
[[ $ambient_proc_root == /proc ]] ||
  fail 'an ambient environment variable replaced the production procfs root'

ambient_loaded_guard=$(
  NXBOOTSTRAP_LIBRARY_LOADED=1 \
    /usr/bin/bash -c \
      'source "$1"; declare -F nxbootstrap_main >/dev/null && printf loaded' \
      _ "$PROJECT_ROOT/nxbootstrap.sh"
)
[[ $ambient_loaded_guard == loaded ]] ||
  fail 'ambient NXBOOTSTRAP_LIBRARY_LOADED skipped the production library'
if NXBOOTSTRAP_CHILD_PID=999 NXBOOTSTRAP_PROC_ROOT=/outside \
    /usr/bin/bash -c \
      'source "$1"; export -p' _ "$PROJECT_ROOT/nxbootstrap.sh" |
      grep -E 'NXBOOTSTRAP_(CHILD_PID|PROC_ROOT)=' >/dev/null; then
  fail 'ambient export attributes leaked internal bootstrap state to children'
fi

# Process-stop logic is exercised against a synthetic proc tree. The signal
# function is replaced after sourcing, so this test cannot reach a real PID.
FAKE_PROC=$TEST_ROOT/fake-proc
SIGNAL_LOG=$TEST_ROOT/intended-signals.txt
mkdir -p "$FAKE_PROC/4242" "$FAKE_PROC/5151"
printf '%s\n' \
  '4242 (owned child) S 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 777' \
  > "$FAKE_PROC/4242/stat"
printf '%s\n' \
  '5151 (unrelated) S 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 888' \
  > "$FAKE_PROC/5151/stat"
/usr/bin/bash -c '
  source "$1"
  NXBOOTSTRAP_PROC_ROOT=$2
  NXBOOTSTRAP_TERM_ATTEMPTS=1
  NXBOOTSTRAP_TERM_DELAY=0
  NXBOOTSTRAP_TEST_SIGNAL_LOG=$3
  nxbootstrap_send_signal() {
    printf "%s:%s\n" "$1" "$2" >> "$NXBOOTSTRAP_TEST_SIGNAL_LOG"
  }
  nxbootstrap_stop_tracked_process 4242 777
' _ "$PROJECT_ROOT/nxbootstrap.sh" "$FAKE_PROC" "$SIGNAL_LOG"
[[ $(<"$SIGNAL_LOG") == $'TERM:4242\nKILL:4242' ]] ||
  fail 'exact-child stop did not emit the expected synthetic TERM/KILL sequence'
if grep -F ':5151' "$SIGNAL_LOG" >/dev/null; then
  fail 'exact-child stop inspected or selected an unrelated synthetic PID'
fi

: > "$SIGNAL_LOG"
/usr/bin/bash -c '
  source "$1"
  NXBOOTSTRAP_PROC_ROOT=$2
  NXBOOTSTRAP_TEST_SIGNAL_LOG=$3
  nxbootstrap_send_signal() {
    printf "%s:%s\n" "$1" "$2" >> "$NXBOOTSTRAP_TEST_SIGNAL_LOG"
  }
  nxbootstrap_stop_tracked_process 4242 999
' _ "$PROJECT_ROOT/nxbootstrap.sh" "$FAKE_PROC" "$SIGNAL_LOG"
[[ ! -s $SIGNAL_LOG ]] ||
  fail 'PID with a mismatched starttime received a synthetic signal'

HUP_FINISH=$TEST_ROOT/hup-finish.txt
set +e
NXBOOTSTRAP_TEST_HUP_FINISH=$HUP_FINISH \
  bash -c '
    source "$1"
    pm_finish() { printf "finished\n" >> "$NXBOOTSTRAP_TEST_HUP_FINISH"; }
    nxbootstrap_install_traps
    nxbootstrap_on_signal 129
  ' _ "$PROJECT_ROOT/nxbootstrap.sh"
hup_status=$?
set -e
[[ $hup_status -eq 129 && $(grep -c '^finished$' "$HUP_FINISH") -eq 1 ]] ||
  fail 'HUP path did not preserve status 129 and finish exactly once'

CLEANUP_FINISH=$TEST_ROOT/cleanup-finish.txt
NXBOOTSTRAP_TEST_CLEANUP_FINISH=$CLEANUP_FINISH \
  bash -c '
    source "$1"
    pm_finish() { printf "finished\n" >> "$NXBOOTSTRAP_TEST_CLEANUP_FINISH"; }
    nxbootstrap_cleanup
    nxbootstrap_cleanup
  ' _ "$PROJECT_ROOT/nxbootstrap.sh"
[[ $(grep -c '^finished$' "$CLEANUP_FINISH") -eq 1 ]] ||
  fail 'cleanup could execute PortMaster finish more than once'

rm -f -- "$GAME_DIR/payload.bin" "$TEST_ROOT/finish.txt"
mv -- "$GAME_DIR/nxextract/run-extractor.sh" \
  "$GAME_DIR/nxextract/run-extractor.saved"
set +e
NXBOOTSTRAP_TEST_RESULT=$RESULT \
NXBOOTSTRAP_TEST_PM_HELPER=$TEST_ROOT/helper.txt \
NXBOOTSTRAP_TEST_PM_FINISH=$TEST_ROOT/finish.txt \
NXBOOTSTRAP_TEST_FOREIGN_EXIT=$TEST_ROOT/foreign-exit.txt \
NXBOOTSTRAP_TEST_ORDER=$TEST_ROOT/order.txt \
NXBOOTSTRAP_PORTMASTER_ROOTS=$PM_DIR \
NXBOOTSTRAP_LOCK_ROOT=$TEST_ROOT/locks \
NXBOOTSTRAP_TEST_NO_TTY=1 \
NXPORT_ID=synthetic NXPORT_TITLE=Synthetic NXPORT_GAME_DIR=$GAME_DIR \
NXPORT_ARCH=x86_64 NXPORT_EXECUTABLE=fake-loader NXPORT_NXEXTRACT=yes \
  bash -c 'source "$1"; nxbootstrap_main' _ "$PROJECT_ROOT/nxbootstrap.sh"
status=$?
set -e
[[ $status -eq 1 ]] || fail 'incomplete NXExtract integration was not rejected'
grep -F 'incomplete NXExtract integration' "$GAME_DIR/debug.log" >/dev/null ||
  fail 'NXExtract error was not recorded'
[[ $(grep -c '^finished$' "$TEST_ROOT/finish.txt") -eq 1 ]] ||
  fail 'error path did not call pm_finish exactly once'

mv -- "$GAME_DIR/debug.log" "$GAME_DIR/debug.saved.log"
printf 'log-victim\n' > "$TEST_ROOT/log-victim"
ln -s "$TEST_ROOT/log-victim" "$GAME_DIR/debug.log"
mkdir -p "$TEST_ROOT/private-tmp"
TMPDIR=$TEST_ROOT/private-tmp NXPORT_ID=synthetic \
NXPORT_GAME_DIR=$GAME_DIR NXPORT_TITLE=Synthetic \
  bash -c 'source "$1"; nxbootstrap_open_log; printf "safe-log\\n"' \
    _ "$PROJECT_ROOT/nxbootstrap.sh"
[[ $(<"$TEST_ROOT/log-victim") == log-victim ]] ||
  fail 'runtime log followed and truncated a symlink target'
grep -Fx 'safe-log' \
  "$TEST_ROOT/private-tmp/nxport-${UID}/synthetic-debug.log" >/dev/null ||
  fail 'unsafe game log did not fall back to the private runtime directory'

rm -f -- "$GAME_DIR/debug.log"
printf 'hardlink-log-victim\n' > "$TEST_ROOT/log-hardlink-victim"
ln "$TEST_ROOT/log-hardlink-victim" "$GAME_DIR/debug.log"
TMPDIR=$TEST_ROOT/private-tmp NXPORT_ID=synthetic \
NXPORT_GAME_DIR=$GAME_DIR NXPORT_TITLE=Synthetic \
  bash -c 'source "$1"; nxbootstrap_open_log; printf "hardlink-safe-log\n"' \
    _ "$PROJECT_ROOT/nxbootstrap.sh"
[[ $(<"$TEST_ROOT/log-hardlink-victim") == hardlink-log-victim ]] ||
  fail 'runtime log truncated or wrote through an unexpected hardlink'
grep -Fx 'hardlink-safe-log' \
  "$TEST_ROOT/private-tmp/nxport-${UID}/synthetic-debug.log" >/dev/null ||
  fail 'hardlinked game log did not fall back to the private runtime directory'

set +e
TMPDIR=$GAME_DIR NXPORT_ID=synthetic NXPORT_TITLE=Synthetic \
NXPORT_GAME_DIR=$GAME_DIR NXPORT_ARCH=x86_64 NXPORT_EXECUTABLE=fake-loader \
  bash -c \
    'source "$1"; nxbootstrap_validate_config; nxbootstrap_private_tmp_root' \
    _ "$PROJECT_ROOT/nxbootstrap.sh" >/dev/null 2>&1
game_tmp_status=$?
set -e
[[ $game_tmp_status -ne 0 ]] ||
  fail 'private runtime tmp was accepted inside the game-data tree'

printf 'tty-victim\n' > "$TEST_ROOT/tty-victim"
CUR_TTY=$TEST_ROOT/tty-victim NXPORT_TITLE=Synthetic \
  bash -c 'source "$1"; nxbootstrap_tty_message unsafe' \
    _ "$PROJECT_ROOT/nxbootstrap.sh"
[[ $(<"$TEST_ROOT/tty-victim") == tty-victim ]] ||
  fail 'diagnostic TTY path truncated a non-character file'

bash -n "$PROJECT_ROOT/nxbootstrap.sh"
printf 'nxbootstrap tests passed\n'
