/*
 * SPDX-License-Identifier: MIT
 *
 * nxsplash-nextos: mandatory, backend-neutral pre-runtime screen for ports
 * generated by the NextOS framework.
 *
 * SDL2 is resolved at runtime so the helper follows the firmware provider.
 * A real inherited/default backend is always attempted first. Advertised
 * backends are considered only after that attempt fails, and a software
 * framebuffer is the graphical last-resort renderer. Failure to draw is
 * fail-open: the fixed hold still completes and the game lifecycle remains
 * untouched.
 */
#ifndef _GNU_SOURCE
#define _GNU_SOURCE
#endif

#include <ctype.h>
#include <dirent.h>
#include <dlfcn.h>
#include <errno.h>
#include <fcntl.h>
#include <linux/fb.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>
#include <sys/ioctl.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <unistd.h>

#ifndef NXSPLASH_DURATION_MS
#define NXSPLASH_DURATION_MS 5000u
#endif
#ifndef NXSPLASH_FBDEV_PATH
#define NXSPLASH_FBDEV_PATH "/dev/fb0"
#endif

#define NXSPLASH_VERSION "0.1.2"
#define MAX_VIDEO_CANDIDATES 24
#define MAX_VIDEO_DRIVER_NAME 64

typedef struct SDL_Window SDL_Window;
typedef struct SDL_Renderer SDL_Renderer;
typedef struct SDL_Rect {
  int x, y, w, h;
} SDL_Rect;
typedef union SDL_Event {
  uint32_t type;
  unsigned char padding[256];
} SDL_Event;

enum {
  SDL_INIT_VIDEO = 0x00000020u,
  SDL_WINDOW_FULLSCREEN_DESKTOP = 0x00001001u,
  SDL_RENDERER_SOFTWARE = 0x00000001u,
  SDL_RENDERER_ACCELERATED = 0x00000002u,
  SDL_RENDERER_PRESENTVSYNC = 0x00000004u,
};

typedef struct Color {
  uint8_t r, g, b, a;
} Color;

typedef struct VideoCandidates {
  char names[MAX_VIDEO_CANDIDATES][MAX_VIDEO_DRIVER_NAME];
  int count;
} VideoCandidates;

static void *sdl_handle;
static int (*pSDL_Init)(uint32_t);
static void (*pSDL_Quit)(void);
static const char *(*pSDL_GetError)(void);
static const char *(*pSDL_GetCurrentVideoDriver)(void);
static int (*pSDL_GetNumVideoDrivers)(void);
static const char *(*pSDL_GetVideoDriver)(int);
static SDL_Window *(*pSDL_CreateWindow)(const char *, int, int, int, int,
                                        uint32_t);
static void (*pSDL_DestroyWindow)(SDL_Window *);
static SDL_Renderer *(*pSDL_CreateRenderer)(SDL_Window *, int, uint32_t);
static void (*pSDL_DestroyRenderer)(SDL_Renderer *);
static int (*pSDL_GetRendererOutputSize)(SDL_Renderer *, int *, int *);
static int (*pSDL_SetRenderDrawColor)(SDL_Renderer *, uint8_t, uint8_t,
                                      uint8_t, uint8_t);
static int (*pSDL_RenderClear)(SDL_Renderer *);
static int (*pSDL_RenderFillRect)(SDL_Renderer *, const SDL_Rect *);
static int (*pSDL_RenderDrawRect)(SDL_Renderer *, const SDL_Rect *);
static void (*pSDL_RenderPresent)(SDL_Renderer *);
static int (*pSDL_PollEvent)(SDL_Event *);
static void (*pSDL_Delay)(uint32_t);

#define SDL_LOAD(symbol)                                                       \
  do {                                                                         \
    *(void **)(&p##symbol) = dlsym(sdl_handle, #symbol);                       \
    if (!p##symbol) {                                                          \
      fprintf(stderr, "nxsplash: missing SDL symbol %s\n", #symbol);          \
      return 0;                                                                \
    }                                                                          \
  } while (0)

static int load_sdl(void) {
  static const char *names[] = {
      "libSDL2-2.0.so.0", "libSDL2.so.0", "libSDL2.so", NULL,
  };
  int index;
  for (index = 0; names[index] && !sdl_handle; index++)
    sdl_handle = dlopen(names[index], RTLD_NOW | RTLD_LOCAL);
  if (!sdl_handle) {
    fprintf(stderr, "nxsplash: SDL2 unavailable\n");
    return 0;
  }
  SDL_LOAD(SDL_Init);
  SDL_LOAD(SDL_Quit);
  SDL_LOAD(SDL_GetError);
  SDL_LOAD(SDL_GetCurrentVideoDriver);
  SDL_LOAD(SDL_GetNumVideoDrivers);
  SDL_LOAD(SDL_GetVideoDriver);
  SDL_LOAD(SDL_CreateWindow);
  SDL_LOAD(SDL_DestroyWindow);
  SDL_LOAD(SDL_CreateRenderer);
  SDL_LOAD(SDL_DestroyRenderer);
  SDL_LOAD(SDL_GetRendererOutputSize);
  SDL_LOAD(SDL_SetRenderDrawColor);
  SDL_LOAD(SDL_RenderClear);
  SDL_LOAD(SDL_RenderFillRect);
  SDL_LOAD(SDL_RenderDrawRect);
  SDL_LOAD(SDL_RenderPresent);
  SDL_LOAD(SDL_PollEvent);
  SDL_LOAD(SDL_Delay);
  return 1;
}

#undef SDL_LOAD

static uint64_t wall_milliseconds(void) {
  struct timeval value;
  if (gettimeofday(&value, NULL) != 0)
    return 0;
  return (uint64_t)value.tv_sec * 1000u + (uint64_t)value.tv_usec / 1000u;
}

static int path_exists(const char *path) {
  struct stat value;
  return path && stat(path, &value) == 0;
}

static int directory_usable(const char *path) {
  struct stat value;
  if (!path || !*path || stat(path, &value) != 0 || !S_ISDIR(value.st_mode))
    return 0;
  return access(path, R_OK | W_OK | X_OK) == 0;
}

static int wayland_socket_exists(void) {
  const char *runtime = getenv("XDG_RUNTIME_DIR");
  const char *display = getenv("WAYLAND_DISPLAY");
  char path[512];
  struct stat value;
  if (!runtime || !*runtime || !display || !*display || strchr(display, '/'))
    return 0;
  if (snprintf(path, sizeof(path), "%s/%s", runtime, display) >=
      (int)sizeof(path))
    return 0;
  return stat(path, &value) == 0 && S_ISSOCK(value.st_mode);
}

/* Reuse an existing firmware session; never start or replace a compositor. */
static void configure_session_runtime(void) {
  char run_user[64], var_run_user[64], run_legacy[64];
  const char *runtime = getenv("XDG_RUNTIME_DIR");
  const char *candidates[6];
  int index;

  snprintf(run_user, sizeof(run_user), "/run/user/%u", (unsigned)getuid());
  snprintf(var_run_user, sizeof(var_run_user), "/var/run/user/%u",
           (unsigned)getuid());
  snprintf(run_legacy, sizeof(run_legacy), "/run/%u-runtime-dir",
           (unsigned)getuid());
  candidates[0] = run_legacy;
  candidates[1] = run_user;
  candidates[2] = var_run_user;
  candidates[3] = "/run/0-runtime-dir";
  candidates[4] = "/var/run/0-runtime-dir";
  candidates[5] = NULL;

  if (!directory_usable(runtime)) {
    for (index = 0; candidates[index]; index++) {
      if (!directory_usable(candidates[index]))
        continue;
      if (setenv("XDG_RUNTIME_DIR", candidates[index], 1) == 0)
        runtime = getenv("XDG_RUNTIME_DIR");
      break;
    }
  }

  if (!wayland_socket_exists() && runtime && *runtime) {
    DIR *directory = opendir(runtime);
    struct dirent *entry;
    if (!directory)
      return;
    while ((entry = readdir(directory)) != NULL) {
      char socket_path[512];
      struct stat value;
      if (strncmp(entry->d_name, "wayland-", 8) != 0 ||
          strstr(entry->d_name, ".lock") != NULL)
        continue;
      if (snprintf(socket_path, sizeof(socket_path), "%s/%s", runtime,
                   entry->d_name) >= (int)sizeof(socket_path))
        continue;
      if (stat(socket_path, &value) != 0 || !S_ISSOCK(value.st_mode))
        continue;
      (void)setenv("WAYLAND_DISPLAY", entry->d_name, 1);
      break;
    }
    closedir(directory);
  }
}

static int driver_is_invisible(const char *name) {
  return name && (!strcasecmp(name, "dummy") ||
                  !strcasecmp(name, "offscreen") ||
                  !strcasecmp(name, "evdev"));
}

static int driver_is_plausible(const char *name) {
  if (!name || !*name || driver_is_invisible(name))
    return 0;
  if (!strcasecmp(name, "wayland"))
    return wayland_socket_exists();
  if (!strcasecmp(name, "x11"))
    return getenv("DISPLAY") && *getenv("DISPLAY");
  if (!strcasecmp(name, "kmsdrm"))
    return path_exists("/dev/dri/card0");
  if (!strcasecmp(name, "mali") || !strcasecmp(name, "fbcon") ||
      !strcasecmp(name, "directfb"))
    return path_exists("/dev/fb0");
  return 1;
}

static void collect_video_candidates(VideoCandidates *candidates) {
  int count = pSDL_GetNumVideoDrivers();
  int index;
  memset(candidates, 0, sizeof(*candidates));
  for (index = 0; index < count &&
                  candidates->count < MAX_VIDEO_CANDIDATES;
       index++) {
    const char *name = pSDL_GetVideoDriver(index);
    int previous, duplicate = 0;
    if (!driver_is_plausible(name))
      continue;
    for (previous = 0; previous < candidates->count; previous++) {
      if (!strcasecmp(candidates->names[previous], name)) {
        duplicate = 1;
        break;
      }
    }
    if (duplicate)
      continue;
    snprintf(candidates->names[candidates->count],
             sizeof(candidates->names[candidates->count]), "%s", name);
    candidates->count++;
  }
}

static int try_renderer(const char *title, SDL_Window **window_out,
                        SDL_Renderer **renderer_out) {
  SDL_Window *window;
  SDL_Renderer *renderer = NULL;
  const char *driver;
  if (pSDL_Init(SDL_INIT_VIDEO) != 0)
    return 0;
  driver = pSDL_GetCurrentVideoDriver();
  if (driver_is_invisible(driver)) {
    pSDL_Quit();
    return 0;
  }
  window = pSDL_CreateWindow(title, 0, 0, 640, 480,
                             SDL_WINDOW_FULLSCREEN_DESKTOP);
  if (window)
    renderer = pSDL_CreateRenderer(
        window, -1, SDL_RENDERER_ACCELERATED | SDL_RENDERER_PRESENTVSYNC);
  if (!renderer && window)
    renderer = pSDL_CreateRenderer(window, -1, SDL_RENDERER_SOFTWARE);
  if (!renderer) {
    if (window)
      pSDL_DestroyWindow(window);
    pSDL_Quit();
    return 0;
  }
  *window_out = window;
  *renderer_out = renderer;
  return 1;
}

/* A few KMSDRM firmwares expose the matching GPU provider through the
 * unversioned runtime names while their versioned EGL soname is only an
 * unusable GLVND dispatcher. Retry those portable names only after the real
 * firmware/default attempt fails, and never replace an explicit provider. */
static int enable_portable_provider_retry(void) {
  if (getenv("SDL_VIDEO_EGL_DRIVER") || getenv("SDL_VIDEO_GL_DRIVER"))
    return 0;
  if (setenv("SDL_VIDEO_EGL_DRIVER", "libEGL.so", 1) != 0)
    return 0;
  if (setenv("SDL_VIDEO_GL_DRIVER", "libGLESv2.so", 1) != 0) {
    unsetenv("SDL_VIDEO_EGL_DRIVER");
    return 0;
  }
  fprintf(stderr, "nxsplash: retrying portable EGL/GLES provider names\n");
  return 1;
}

static void drop_portable_provider_retry(void) {
  unsetenv("SDL_VIDEO_EGL_DRIVER");
  unsetenv("SDL_VIDEO_GL_DRIVER");
}

/* Default/inherited selection is authoritative. Fallback is evidence-driven. */
static int create_renderer(const char *title, SDL_Window **window_out,
                           SDL_Renderer **renderer_out) {
  VideoCandidates candidates;
  char inherited[MAX_VIDEO_DRIVER_NAME];
  int index;

  inherited[0] = 0;
  if (getenv("SDL_VIDEODRIVER") && *getenv("SDL_VIDEODRIVER"))
    snprintf(inherited, sizeof(inherited), "%s", getenv("SDL_VIDEODRIVER"));
  if (try_renderer(title, window_out, renderer_out))
    return 1;

  collect_video_candidates(&candidates);
  unsetenv("SDL_VIDEODRIVER");
  if (inherited[0] && try_renderer(title, window_out, renderer_out)) {
    fprintf(stderr, "nxsplash: inherited backend failed; automatic backend recovered\n");
    return 1;
  }
  for (index = 0; index < candidates.count; index++) {
    if (inherited[0] && !strcasecmp(inherited, candidates.names[index]))
      continue;
    if (setenv("SDL_VIDEODRIVER", candidates.names[index], 1) != 0)
      continue;
    if (try_renderer(title, window_out, renderer_out)) {
      fprintf(stderr, "nxsplash: recovered with advertised backend=%s\n",
              candidates.names[index]);
      return 1;
    }
  }
  unsetenv("SDL_VIDEODRIVER");

  if (!enable_portable_provider_retry())
    return 0;
  if (inherited[0])
    (void)setenv("SDL_VIDEODRIVER", inherited, 1);
  if (try_renderer(title, window_out, renderer_out)) {
    fprintf(stderr,
            "nxsplash: recovered with portable EGL/GLES provider names\n");
    return 1;
  }
  unsetenv("SDL_VIDEODRIVER");
  if (inherited[0] && try_renderer(title, window_out, renderer_out)) {
    fprintf(stderr,
            "nxsplash: portable provider recovered automatic backend\n");
    return 1;
  }
  for (index = 0; index < candidates.count; index++) {
    if (setenv("SDL_VIDEODRIVER", candidates.names[index], 1) != 0)
      continue;
    if (try_renderer(title, window_out, renderer_out)) {
      fprintf(stderr,
              "nxsplash: portable provider recovered backend=%s\n",
              candidates.names[index]);
      return 1;
    }
  }
  unsetenv("SDL_VIDEODRIVER");
  drop_portable_provider_retry();
  return 0;
}

/* Five-bit rows, seven rows per glyph. */
static const uint8_t letter_rows[26][7] = {
    {14, 17, 17, 31, 17, 17, 17}, {30, 17, 17, 30, 17, 17, 30},
    {14, 17, 16, 16, 16, 17, 14}, {30, 17, 17, 17, 17, 17, 30},
    {31, 16, 16, 30, 16, 16, 31}, {31, 16, 16, 30, 16, 16, 16},
    {14, 17, 16, 23, 17, 17, 14}, {17, 17, 17, 31, 17, 17, 17},
    {14, 4, 4, 4, 4, 4, 14},      {1, 1, 1, 1, 17, 17, 14},
    {17, 18, 20, 24, 20, 18, 17}, {16, 16, 16, 16, 16, 16, 31},
    {17, 27, 21, 21, 17, 17, 17}, {17, 25, 21, 19, 17, 17, 17},
    {14, 17, 17, 17, 17, 17, 14}, {30, 17, 17, 30, 16, 16, 16},
    {14, 17, 17, 17, 21, 18, 13}, {30, 17, 17, 30, 20, 18, 17},
    {15, 16, 16, 14, 1, 1, 30},   {31, 4, 4, 4, 4, 4, 4},
    {17, 17, 17, 17, 17, 17, 14}, {17, 17, 17, 17, 17, 10, 4},
    {17, 17, 17, 21, 21, 21, 10}, {17, 17, 10, 4, 10, 17, 17},
    {17, 17, 10, 4, 4, 4, 4},     {31, 1, 2, 4, 8, 16, 31},
};

static const uint8_t number_rows[10][7] = {
    {14, 17, 19, 21, 25, 17, 14}, {4, 12, 4, 4, 4, 4, 14},
    {14, 17, 1, 2, 4, 8, 31},     {30, 1, 1, 14, 1, 1, 30},
    {2, 6, 10, 18, 31, 2, 2},     {31, 16, 16, 30, 1, 1, 30},
    {6, 8, 16, 30, 17, 17, 14},   {31, 1, 2, 4, 8, 8, 8},
    {14, 17, 17, 14, 17, 17, 14}, {14, 17, 17, 15, 1, 2, 12},
};

static const uint8_t blank_rows[7] = {0, 0, 0, 0, 0, 0, 0};
static const uint8_t question_rows[7] = {14, 17, 1, 2, 4, 0, 4};
static const uint8_t colon_rows[7] = {0, 4, 4, 0, 4, 4, 0};
static const uint8_t dash_rows[7] = {0, 0, 0, 31, 0, 0, 0};
static const uint8_t dot_rows[7] = {0, 0, 0, 0, 0, 6, 6};
static const uint8_t slash_rows[7] = {1, 2, 2, 4, 8, 8, 16};
static const uint8_t gt_rows[7] = {16, 8, 4, 2, 4, 8, 16};
static const uint8_t lb_rows[7] = {14, 8, 8, 8, 8, 8, 14};
static const uint8_t rb_rows[7] = {14, 2, 2, 2, 2, 2, 14};
static const uint8_t hash_rows[7] = {10, 31, 10, 10, 31, 10, 0};
static const uint8_t underscore_rows[7] = {0, 0, 0, 0, 0, 0, 31};

static const uint8_t *glyph_rows(unsigned character) {
  if (character >= 'a' && character <= 'z')
    character = (unsigned)toupper((int)character);
  if (character >= 'A' && character <= 'Z')
    return letter_rows[character - 'A'];
  if (character >= '0' && character <= '9')
    return number_rows[character - '0'];
  switch (character) {
  case ' ': return blank_rows;
  case ':': return colon_rows;
  case '-': return dash_rows;
  case '.': return dot_rows;
  case '/': return slash_rows;
  case '>': return gt_rows;
  case '[': return lb_rows;
  case ']': return rb_rows;
  case '#': return hash_rows;
  case '_': return underscore_rows;
  default: return question_rows;
  }
}

static void sanitize_title(const char *input, char *output, size_t capacity) {
  size_t used = 0;
  const unsigned char *cursor = (const unsigned char *)(input ? input : "GAME");
  while (*cursor && used + 1 < capacity) {
    unsigned char value = *cursor++;
    if (value < 0x20 || value == 0x7f)
      continue;
    if (value < 0x80) {
      output[used++] = (char)value;
      continue;
    }
    /* Public titles may contain UTF-8; keep the display deterministic/ASCII. */
    while ((*cursor & 0xc0u) == 0x80u)
      cursor++;
    output[used++] = '?';
  }
  output[used] = 0;
  if (!used)
    snprintf(output, capacity, "GAME");
}

static int text_width(const char *text, int scale) {
  size_t length = strlen(text);
  return length ? (int)length * 6 * scale - scale : 0;
}

static void ellipsize(char *text, size_t capacity, int max_characters) {
  size_t length = strlen(text);
  if (max_characters < 1) {
    text[0] = 0;
    return;
  }
  if ((size_t)max_characters >= length)
    return;
  if ((size_t)max_characters >= capacity)
    max_characters = (int)capacity - 1;
  if (max_characters <= 3) {
    memset(text, '.', (size_t)max_characters);
    text[max_characters] = 0;
    return;
  }
  memcpy(text + max_characters - 3, "...", 4);
}

static void set_color(SDL_Renderer *renderer, Color color) {
  (void)pSDL_SetRenderDrawColor(renderer, color.r, color.g, color.b, color.a);
}

static void fill(SDL_Renderer *renderer, int x, int y, int width, int height,
                 Color color) {
  SDL_Rect rect = {x, y, width, height};
  if (width <= 0 || height <= 0)
    return;
  set_color(renderer, color);
  (void)pSDL_RenderFillRect(renderer, &rect);
}

static void outline(SDL_Renderer *renderer, int x, int y, int width, int height,
                    Color color) {
  SDL_Rect rect = {x, y, width, height};
  set_color(renderer, color);
  (void)pSDL_RenderDrawRect(renderer, &rect);
}

static void draw_text(SDL_Renderer *renderer, int x, int y, int scale,
                      const char *text, Color color) {
  SDL_Rect pixel = {0, 0, scale, scale};
  set_color(renderer, color);
  while (*text) {
    const uint8_t *rows = glyph_rows((unsigned char)*text++);
    int row, column;
    for (row = 0; row < 7; row++) {
      for (column = 0; column < 5; column++) {
        if (rows[row] & (1u << (4 - column))) {
          pixel.x = x + column * scale;
          pixel.y = y + row * scale;
          (void)pSDL_RenderFillRect(renderer, &pixel);
        }
      }
    }
    x += 6 * scale;
  }
}

static void draw_centered(SDL_Renderer *renderer, int center, int y, int scale,
                          const char *text, Color color) {
  draw_text(renderer, center - text_width(text, scale) / 2, y, scale, text,
            color);
}

static void draw_screen(SDL_Renderer *renderer, int width, int height,
                        const char *title, uint64_t elapsed) {
  const Color desktop = {18, 22, 29, 255};
  const Color shadow = {2, 4, 7, 255};
  const Color terminal = {5, 9, 11, 255};
  const Color titlebar = {37, 44, 54, 255};
  const Color border = {91, 105, 120, 255};
  const Color green = {77, 232, 151, 255};
  const Color cyan = {91, 201, 245, 255};
  const Color white = {230, 238, 242, 255};
  const Color dim = {135, 153, 159, 255};
  int margin = width / 24;
  int panel_x, panel_y, panel_w, panel_h, bar_h;
  int base, logo_scale, left, line_y, gap, max_chars;
  unsigned remaining, progress;
  char game_line[192], loading_line[96], shown_title[128];

  if (margin < 7)
    margin = 7;
  if (margin > 48)
    margin = 48;
  panel_x = margin;
  panel_y = height / 14;
  panel_w = width - margin * 2;
  panel_h = height - panel_y * 2;
  bar_h = height < 300 ? 18 : (height < 600 ? 28 : 38);
  base = height < 300 ? 1 : (height < 650 ? 2 : 3);
  logo_scale = base + 1;

  fill(renderer, 0, 0, width, height, desktop);
  fill(renderer, panel_x + 5, panel_y + 6, panel_w, panel_h, shadow);
  fill(renderer, panel_x, panel_y, panel_w, panel_h, terminal);
  outline(renderer, panel_x, panel_y, panel_w, panel_h, border);
  fill(renderer, panel_x + 1, panel_y + 1, panel_w - 2, bar_h, titlebar);
  fill(renderer, panel_x + base * 5, panel_y + bar_h / 2 - base * 2,
       base * 4, base * 4, green);
  draw_text(renderer, panel_x + base * 13,
            panel_y + (bar_h - base * 7) / 2, base,
            "NEXTOS BOOT TERMINAL", white);

  left = panel_x + panel_w / 15;
  line_y = panel_y + bar_h + panel_h / 15;
  draw_centered(renderer, panel_x + panel_w / 2, line_y, logo_scale,
                "NEXT OS", green);
  line_y += logo_scale * 8 + panel_h / 24;

  snprintf(shown_title, sizeof(shown_title), "%s", title);
  max_chars = (panel_w - panel_w / 8) / (6 * base) - 15;
  if (max_chars < 8)
    max_chars = 8;
  ellipsize(shown_title, sizeof(shown_title), max_chars);
  snprintf(game_line, sizeof(game_line), "> GAME / JOGO: %s", shown_title);
  gap = base * (height < 300 ? 10 : 11);
  draw_text(renderer, left, line_y, base, game_line, cyan);
  line_y += gap;
  draw_text(renderer, left, line_y, base,
            "> DATA VERIFIED / DADOS VERIFICADOS", white);
  line_y += gap;
  if (height >= 270) {
    draw_text(renderer, left, line_y, base,
              "> CONTROLS READY / CONTROLES PRONTOS", white);
    line_y += gap;
  }
  draw_text(renderer, left, line_y, base,
            "> INITIALIZING GAME / INICIALIZANDO JOGO", white);
  line_y += gap;

  if (elapsed >= NXSPLASH_DURATION_MS)
    remaining = 0;
  else
    remaining = (unsigned)((NXSPLASH_DURATION_MS - elapsed + 999u) / 1000u);
  progress = elapsed >= NXSPLASH_DURATION_MS
                 ? 20u
                 : (unsigned)(elapsed * 20u / NXSPLASH_DURATION_MS);
  {
    char bar[21];
    unsigned index;
    for (index = 0; index < 20; index++)
      bar[index] = index < progress ? '#' : '-';
    bar[20] = 0;
    snprintf(loading_line, sizeof(loading_line),
             "> LOADING / CARREGANDO [%s] %u", bar, remaining);
  }
  draw_text(renderer, left, line_y, base, loading_line, green);
  draw_centered(renderer, panel_x + panel_w / 2,
                panel_y + panel_h - base * 11, base,
                "RETRO ELITE", dim);
}

static void run_sdl_splash(SDL_Renderer *renderer, const char *title) {
  uint64_t start = wall_milliseconds();
  uint64_t elapsed = 0;
  while (elapsed < NXSPLASH_DURATION_MS) {
    SDL_Event event;
    int width = 640, height = 480;
    while (pSDL_PollEvent(&event))
      ;
    if (pSDL_GetRendererOutputSize(renderer, &width, &height) != 0 ||
        width < 160 || height < 120) {
      width = 640;
      height = 480;
    }
    draw_screen(renderer, width, height, title, elapsed);
    pSDL_RenderPresent(renderer);
    pSDL_Delay(33);
    elapsed = wall_milliseconds() - start;
  }
  (void)pSDL_SetRenderDrawColor(renderer, 0, 0, 0, 255);
  (void)pSDL_RenderClear(renderer);
  pSDL_RenderPresent(renderer);
}

typedef struct SoftwareSurface {
  Color *pixels;
  int width;
  int height;
  Color color;
} SoftwareSurface;

typedef struct FramebufferTarget {
  int descriptor;
  unsigned char *mapping;
  size_t mapping_length;
  int writeback;
  struct fb_fix_screeninfo fixed;
  struct fb_var_screeninfo variable;
  SoftwareSurface surface;
} FramebufferTarget;

static int software_surface_init(SoftwareSurface *surface, int width,
                                 int height) {
  size_t count;
  if (!surface || width < 160 || height < 120 || width > 8192 ||
      height > 8192)
    return 0;
  count = (size_t)width * (size_t)height;
  if (count > SIZE_MAX / sizeof(*surface->pixels))
    return 0;
  memset(surface, 0, sizeof(*surface));
  surface->pixels = calloc(count, sizeof(*surface->pixels));
  if (!surface->pixels)
    return 0;
  surface->width = width;
  surface->height = height;
  return 1;
}

static void software_surface_destroy(SoftwareSurface *surface) {
  if (!surface)
    return;
  free(surface->pixels);
  memset(surface, 0, sizeof(*surface));
}

static int software_set_draw_color(SDL_Renderer *renderer, uint8_t red,
                                   uint8_t green, uint8_t blue,
                                   uint8_t alpha) {
  SoftwareSurface *surface = (SoftwareSurface *)renderer;
  surface->color = (Color){red, green, blue, alpha};
  return 0;
}

static int software_fill_rect(SDL_Renderer *renderer, const SDL_Rect *rect) {
  SoftwareSurface *surface = (SoftwareSurface *)renderer;
  int64_t right, bottom;
  int left, top, clipped_right, clipped_bottom, x, y;
  if (!surface || !surface->pixels || !rect || rect->w <= 0 || rect->h <= 0)
    return 0;
  right = (int64_t)rect->x + (int64_t)rect->w;
  bottom = (int64_t)rect->y + (int64_t)rect->h;
  if (right <= 0 || bottom <= 0 || rect->x >= surface->width ||
      rect->y >= surface->height)
    return 0;
  left = rect->x < 0 ? 0 : rect->x;
  top = rect->y < 0 ? 0 : rect->y;
  clipped_right = right > surface->width ? surface->width : (int)right;
  clipped_bottom = bottom > surface->height ? surface->height : (int)bottom;
  for (y = top; y < clipped_bottom; y++) {
    Color *row = surface->pixels + (size_t)y * (size_t)surface->width;
    for (x = left; x < clipped_right; x++)
      row[x] = surface->color;
  }
  return 0;
}

static int software_draw_rect(SDL_Renderer *renderer, const SDL_Rect *rect) {
  SDL_Rect edge;
  if (!rect || rect->w <= 0 || rect->h <= 0)
    return 0;
  edge = (SDL_Rect){rect->x, rect->y, rect->w, 1};
  (void)software_fill_rect(renderer, &edge);
  if (rect->h > 1) {
    edge = (SDL_Rect){rect->x, rect->y + rect->h - 1, rect->w, 1};
    (void)software_fill_rect(renderer, &edge);
  }
  if (rect->h > 2) {
    edge = (SDL_Rect){rect->x, rect->y + 1, 1, rect->h - 2};
    (void)software_fill_rect(renderer, &edge);
    if (rect->w > 1) {
      edge = (SDL_Rect){rect->x + rect->w - 1, rect->y + 1, 1,
                        rect->h - 2};
      (void)software_fill_rect(renderer, &edge);
    }
  }
  return 0;
}

static void draw_software_frame(SoftwareSurface *surface, const char *title,
                                uint64_t elapsed) {
  int (*saved_set_color)(SDL_Renderer *, uint8_t, uint8_t, uint8_t, uint8_t) =
      pSDL_SetRenderDrawColor;
  int (*saved_fill_rect)(SDL_Renderer *, const SDL_Rect *) =
      pSDL_RenderFillRect;
  int (*saved_draw_rect)(SDL_Renderer *, const SDL_Rect *) =
      pSDL_RenderDrawRect;
  pSDL_SetRenderDrawColor = software_set_draw_color;
  pSDL_RenderFillRect = software_fill_rect;
  pSDL_RenderDrawRect = software_draw_rect;
  draw_screen((SDL_Renderer *)surface, surface->width, surface->height, title,
              elapsed);
  pSDL_SetRenderDrawColor = saved_set_color;
  pSDL_RenderFillRect = saved_fill_rect;
  pSDL_RenderDrawRect = saved_draw_rect;
}

static int framebuffer_channel_valid(struct fb_bitfield field,
                                     uint32_t bits_per_pixel,
                                     int allow_empty) {
  if (field.length == 0u)
    return allow_empty;
  return field.length <= 16u && field.offset < bits_per_pixel &&
         field.offset + field.length <= bits_per_pixel && !field.msb_right;
}

static int framebuffer_layout_valid(const struct fb_fix_screeninfo *fixed,
                                    const struct fb_var_screeninfo *variable,
                                    size_t *visible_end) {
  uint32_t bytes_per_pixel;
  size_t row_offset, pixel_offset, end;
  if (!fixed || !variable || !visible_end ||
      fixed->type != FB_TYPE_PACKED_PIXELS ||
      fixed->visual != FB_VISUAL_TRUECOLOR ||
      (variable->bits_per_pixel != 16u && variable->bits_per_pixel != 24u &&
       variable->bits_per_pixel != 32u) ||
      variable->xres < 160u || variable->yres < 120u ||
      variable->xres > 8192u || variable->yres > 8192u ||
      variable->xoffset > variable->xres_virtual ||
      variable->yoffset > variable->yres_virtual ||
      variable->xres > variable->xres_virtual - variable->xoffset ||
      variable->yres > variable->yres_virtual - variable->yoffset ||
      !framebuffer_channel_valid(variable->red, variable->bits_per_pixel, 0) ||
      !framebuffer_channel_valid(variable->green, variable->bits_per_pixel, 0) ||
      !framebuffer_channel_valid(variable->blue, variable->bits_per_pixel, 0) ||
      !framebuffer_channel_valid(variable->transp, variable->bits_per_pixel, 1))
    return 0;
  bytes_per_pixel = variable->bits_per_pixel / 8u;
  if ((size_t)fixed->line_length <
      (size_t)(variable->xoffset + variable->xres) *
          (size_t)bytes_per_pixel)
    return 0;
  row_offset = (size_t)(variable->yoffset + variable->yres - 1u) *
               (size_t)fixed->line_length;
  pixel_offset = (size_t)(variable->xoffset + variable->xres) *
                 (size_t)bytes_per_pixel;
  if (row_offset > SIZE_MAX - pixel_offset)
    return 0;
  end = row_offset + pixel_offset;
  if (fixed->smem_len == 0u || end > (size_t)fixed->smem_len)
    return 0;
  *visible_end = end;
  return 1;
}

static uint32_t framebuffer_channel(uint8_t value, struct fb_bitfield field) {
  uint32_t maximum;
  if (field.length == 0u)
    return 0u;
  maximum = (1u << field.length) - 1u;
  return (((uint32_t)value * maximum + 127u) / 255u) << field.offset;
}

static uint32_t framebuffer_pixel(const struct fb_var_screeninfo *variable,
                                  Color color) {
  return framebuffer_channel(color.r, variable->red) |
         framebuffer_channel(color.g, variable->green) |
         framebuffer_channel(color.b, variable->blue) |
         framebuffer_channel(color.a, variable->transp);
}

static int framebuffer_write_at(int descriptor, const unsigned char *buffer,
                                size_t length, size_t offset) {
  size_t done = 0;
  if (offset > (size_t)INT64_MAX ||
      lseek(descriptor, (off_t)offset, SEEK_SET) < 0)
    return 0;
  while (done < length) {
    ssize_t written = write(descriptor, buffer + done, length - done);
    if (written < 0) {
      if (errno == EINTR)
        continue;
      return 0;
    }
    if (!written)
      return 0;
    done += (size_t)written;
  }
  return 1;
}

static int framebuffer_present(FramebufferTarget *target) {
  uint32_t bytes_per_pixel = target->variable.bits_per_pixel / 8u;
  size_t row_bytes =
      (size_t)target->variable.xres * (size_t)bytes_per_pixel;
  int x, y;
  for (y = 0; y < target->surface.height; y++) {
    unsigned char *destination =
        target->mapping +
        (size_t)(target->variable.yoffset + (uint32_t)y) *
            (size_t)target->fixed.line_length +
        (size_t)target->variable.xoffset * (size_t)bytes_per_pixel;
    const Color *source = target->surface.pixels +
                          (size_t)y * (size_t)target->surface.width;
    for (x = 0; x < target->surface.width; x++) {
      uint32_t pixel = framebuffer_pixel(&target->variable, source[x]);
      memcpy(destination + (size_t)x * (size_t)bytes_per_pixel, &pixel,
             bytes_per_pixel);
    }
  }
  if (target->writeback) {
    size_t first = (size_t)target->variable.yoffset *
                       (size_t)target->fixed.line_length +
                   (size_t)target->variable.xoffset *
                       (size_t)bytes_per_pixel;
    if (row_bytes == (size_t)target->fixed.line_length) {
      size_t length = (size_t)(target->variable.yres - 1u) *
                          (size_t)target->fixed.line_length +
                      row_bytes;
      if (!framebuffer_write_at(target->descriptor, target->mapping + first,
                                length, first))
        return 0;
    } else {
      for (y = 0; y < target->surface.height; y++) {
        size_t offset = first +
                        (size_t)y * (size_t)target->fixed.line_length;
        if (!framebuffer_write_at(target->descriptor,
                                  target->mapping + offset, row_bytes,
                                  offset))
          return 0;
      }
    }
    (void)fsync(target->descriptor);
  }
  __sync_synchronize();
  return 1;
}

static void close_framebuffer(FramebufferTarget *target) {
  if (!target)
    return;
  software_surface_destroy(&target->surface);
  if (target->mapping && target->mapping != MAP_FAILED) {
    if (target->writeback)
      free(target->mapping);
    else
      (void)munmap(target->mapping, target->mapping_length);
  }
  if (target->descriptor >= 0)
    close(target->descriptor);
  memset(target, 0, sizeof(*target));
  target->descriptor = -1;
}

static int open_framebuffer(FramebufferTarget *target) {
  static const char path[] = NXSPLASH_FBDEV_PATH;
  struct stat value;
  size_t visible_end;
  memset(target, 0, sizeof(*target));
  target->descriptor = -1;
  if (lstat(path, &value) != 0 || !S_ISCHR(value.st_mode) ||
      S_ISLNK(value.st_mode))
    return 0;
  target->descriptor = open(path, O_RDWR | O_NOCTTY | O_CLOEXEC);
  if (target->descriptor < 0)
    return 0;
  if (ioctl(target->descriptor, FBIOGET_FSCREENINFO, &target->fixed) != 0 ||
      ioctl(target->descriptor, FBIOGET_VSCREENINFO, &target->variable) != 0 ||
      !framebuffer_layout_valid(&target->fixed, &target->variable,
                                &visible_end)) {
    close_framebuffer(target);
    return 0;
  }
  target->mapping_length = (size_t)target->fixed.smem_len;
  target->mapping = mmap(NULL, target->mapping_length, PROT_READ | PROT_WRITE,
                         MAP_SHARED, target->descriptor, 0);
  if (target->mapping == MAP_FAILED) {
    target->mapping = calloc(1u, target->mapping_length);
    if (!target->mapping) {
      close_framebuffer(target);
      return 0;
    }
    target->writeback = 1;
    fprintf(stderr,
            "nxsplash: fbdev mmap unavailable; using graphical writeback\n");
  }
  if (!software_surface_init(&target->surface, (int)target->variable.xres,
                             (int)target->variable.yres)) {
    close_framebuffer(target);
    return 0;
  }
  (void)visible_end;
  return 1;
}

static void run_fbdev_splash(FramebufferTarget *target, const char *title) {
  uint64_t start = wall_milliseconds();
  uint64_t elapsed = 0;
  while (elapsed < NXSPLASH_DURATION_MS) {
    draw_software_frame(&target->surface, title, elapsed);
    if (!framebuffer_present(target)) {
      fprintf(stderr, "nxsplash: fbdev writeback failed: %s\n",
              strerror(errno));
      break;
    }
    usleep(50000);
    elapsed = wall_milliseconds() - start;
  }
  target->surface.color = (Color){0, 0, 0, 255};
  {
    SDL_Rect screen = {0, 0, target->surface.width, target->surface.height};
    (void)software_fill_rect((SDL_Renderer *)&target->surface, &screen);
  }
  (void)framebuffer_present(target);
  elapsed = wall_milliseconds() - start;
  if (elapsed < NXSPLASH_DURATION_MS)
    usleep((useconds_t)((NXSPLASH_DURATION_MS - elapsed) * 1000u));
}

static int open_console_path(const char *path) {
  struct stat value;
  int descriptor;
  if (!path || path[0] != '/' || lstat(path, &value) != 0 ||
      !S_ISCHR(value.st_mode) || S_ISLNK(value.st_mode))
    return -1;
  descriptor = open(path, O_WRONLY | O_NOCTTY | O_CLOEXEC);
  return descriptor;
}

static int open_console(char *selected, size_t selected_capacity) {
  const char *configured = getenv("NX_SPLASH_TTY");
  const char *diagnostic = getenv("NX_SPLASH_TTY_DIAGNOSTIC");
  int descriptor;

  if (!diagnostic || strcmp(diagnostic, "1") != 0 || !configured ||
      !*configured)
    return -1;
  descriptor = open_console_path(configured);
  if (descriptor >= 0)
    (void)snprintf(selected, selected_capacity, "%s", configured);
  return descriptor;
}

static void run_console_splash(int descriptor, const char *title) {
  uint64_t start = wall_milliseconds();
  uint64_t elapsed = 0;
  char line[512];
  (void)dprintf(descriptor,
                "\033[?25l\033[2J\033[H"
                "+------------------------------------------------------+\r\n"
                "| NEXTOS BOOT TERMINAL                               |\r\n"
                "+------------------------------------------------------+\r\n"
                "|                                                      |\r\n"
                "|                       NEXT OS                        |\r\n"
                "|                                                      |\r\n"
                "| > GAME / JOGO: %-36.36s |\r\n"
                "| > DATA VERIFIED / DADOS VERIFICADOS                 |\r\n"
                "| > CONTROLS READY / CONTROLES PRONTOS                |\r\n"
                "| > INITIALIZING GAME / INICIALIZANDO JOGO            |\r\n"
                "| > LOADING / CARREGANDO [--------------------] 5     |\r\n"
                "|                                                      |\r\n"
                "|                     RETRO ELITE                      |\r\n"
                "+------------------------------------------------------+\r\n",
                title);
  while (elapsed < NXSPLASH_DURATION_MS) {
    unsigned remaining =
        (unsigned)((NXSPLASH_DURATION_MS - elapsed + 999u) / 1000u);
    unsigned filled = (unsigned)(elapsed * 20u / NXSPLASH_DURATION_MS);
    char bar[21];
    unsigned index;
    for (index = 0; index < 20; index++)
      bar[index] = index < filled ? '#' : '-';
    bar[20] = 0;
    snprintf(line, sizeof(line),
             "\033[4A\r\033[K| > LOADING / CARREGANDO [%-20s] %u     |"
             "\033[4B\r",
             bar, remaining);
    (void)write(descriptor, line, strlen(line));
    usleep(100000);
    elapsed = wall_milliseconds() - start;
  }
  (void)dprintf(descriptor,
                "\033[4A\r\033[K"
                "| > LOADING / CARREGANDO [####################] 0     |"
                "\033[4B\r");
  usleep(80000);
  (void)dprintf(descriptor, "\033[0m\033[?25h\033[2J\033[H");
}

static void hold_without_renderer(void) {
  uint64_t start = wall_milliseconds();
  while (wall_milliseconds() - start < NXSPLASH_DURATION_MS)
    usleep(100000);
}

int main(int argc, char **argv) {
  SDL_Window *window = NULL;
  SDL_Renderer *renderer = NULL;
  char title[128];
  char console_path[96] = "unknown";
  int console;
  FramebufferTarget framebuffer;

  if (argc == 2 && strcmp(argv[1], "--version") == 0) {
    printf("nxsplash %s\n", NXSPLASH_VERSION);
    return 0;
  }
  if (argc != 2) {
    fprintf(stderr, "usage: nxsplash-nextos GAME_TITLE\n");
    return 2;
  }
  sanitize_title(argv[1], title, sizeof(title));
  configure_session_runtime();

  if (load_sdl() && create_renderer(title, &window, &renderer)) {
    const char *driver = pSDL_GetCurrentVideoDriver();
    fprintf(stderr, "nxsplash: renderer=sdl driver=%s duration_ms=%u\n",
            driver ? driver : "unknown", (unsigned)NXSPLASH_DURATION_MS);
    run_sdl_splash(renderer, title);
    pSDL_DestroyRenderer(renderer);
    pSDL_DestroyWindow(window);
    pSDL_Quit();
    dlclose(sdl_handle);
    return 0;
  }
  if (sdl_handle) {
    dlclose(sdl_handle);
    sdl_handle = NULL;
  }

  console = open_console(console_path, sizeof(console_path));
  if (console >= 0) {
    fprintf(stderr,
            "nxsplash: renderer=tty diagnostic=1 path=%s duration_ms=%u\n",
            console_path, (unsigned)NXSPLASH_DURATION_MS);
    run_console_splash(console, title);
    close(console);
  } else if (open_framebuffer(&framebuffer)) {
    fprintf(stderr,
            "nxsplash: renderer=fbdev path=/dev/fb0 size=%ux%u bpp=%u "
            "duration_ms=%u\n",
            framebuffer.variable.xres, framebuffer.variable.yres,
            framebuffer.variable.bits_per_pixel,
            (unsigned)NXSPLASH_DURATION_MS);
    run_fbdev_splash(&framebuffer, title);
    close_framebuffer(&framebuffer);
  } else {
    fprintf(stderr,
            "nxsplash: renderer=none; preserving fixed handoff duration_ms=%u\n",
            (unsigned)NXSPLASH_DURATION_MS);
    hold_without_renderer();
  }
  return 0;
}
