#!/usr/bin/env python3
"""Name the PLT slots PairIP hides, from a donor Android process.

The protected objects ship .rela.plt entries for only part of their PLT, so a
loader that only applies relocations leaves the rest holding the link-time PLT0
address.  On Android those slots are filled by PairIP's interpreter at load
time.  This reads the filled GOT out of a donor process, maps each address back
to (system library, exported symbol) and writes the slot -> name table the port
uses to fill the same slots natively.
"""
import re, struct, sys, os

CAP = os.path.dirname(os.path.abspath(__file__))

# bionic picks an implementation for these at load time through an ifunc, so
# what lands in the GOT is the implementation's private name.  memcpy's
# implementation also serves memmove; binding it as memmove is correct for both
# and never wrong for an overlapping copy.
IFUNC_ALIAS = {
    '__memchr_aarch64': 'memchr',
    '__memcmp_aarch64': 'memcmp',
    '__memcpy_aarch64_simd': 'memmove',
    '__memcpy_aarch64': 'memmove',
    '__memmove_aarch64_simd': 'memmove',
    '__memmove_aarch64': 'memmove',
    '__memrchr_aarch64': 'memrchr',
    '__memset_aarch64': 'memset',
    '__stpcpy_aarch64': 'stpcpy',
    '__strchr_aarch64': 'strchr',
    '__strchrnul_aarch64': 'strchrnul',
    '__strcmp_aarch64': 'strcmp',
    '__strcpy_aarch64': 'strcpy',
    '__strlen_aarch64': 'strlen',
    '__strncmp_aarch64': 'strncmp',
    '__strnlen_aarch64': 'strnlen',
    '__strrchr_aarch64': 'strrchr',
}

def load_maps(path):
    out = []
    for line in open(path):
        m = re.match(r"([0-9a-f]+)-([0-9a-f]+) (\S+) ([0-9a-f]+) \S+ \d+\s*(.*)",
                     line.strip())
        if m:
            out.append((int(m.group(1), 16), int(m.group(2), 16),
                        int(m.group(4), 16), m.group(5)))
    return out

def module_bases(maps):
    base = {}
    for lo, hi, off, path in maps:
        if not path or path.startswith('['):
            continue
        if path not in base or lo - off < base[path]:
            base[path] = lo - off
    return base

def dynsyms(path):
    d = open(path, 'rb').read()
    e_shoff, = struct.unpack_from('<Q', d, 0x28)
    e_shentsize, e_shnum, e_shstrndx = struct.unpack_from('<HHH', d, 0x3a)
    secs = []
    for i in range(e_shnum):
        o = e_shoff + i * e_shentsize
        name, typ, flags, addr, off, size, link, info, align, entsize = \
            struct.unpack_from('<IIQQQQIIQQ', d, o)
        secs.append((name, typ, addr, off, size, link, entsize))
    out = {}
    # Both tables: bionic resolves memcpy and friends through ifuncs, so the
    # address in the GOT is the chosen implementation (__memcpy_aarch64_simd),
    # which only .symtab names.
    for name, typ, addr, off, size, link, entsize in secs:
        if typ not in (2, 11):   # SHT_SYMTAB, SHT_DYNSYM
            continue
        stroff = secs[link][3]
        strsz = secs[link][4]
        strtab = d[stroff:stroff + strsz]
        for k in range(size // 24):
            st_name, st_info, st_other, st_shndx, st_value, st_size = \
                struct.unpack_from('<IBBHQQ', d, off + k * 24)
            if st_shndx == 0 or not st_value:
                continue
            end = strtab.index(b'\0', st_name)
            sym = strtab[st_name:end].decode('utf-8', 'replace')
            if sym.startswith('$'):      # ARM mapping symbols, not code
                continue
            out.setdefault(st_value, IFUNC_ALIAS.get(sym, sym))
    return out

def main():
    maps = load_maps(os.path.join(CAP, 'donor-maps.txt'))
    bases = module_bases(maps)
    cache = {}

    def name_of(addr):
        for lo, hi, off, path in maps:
            if not (lo <= addr < hi) or not path:
                continue
            local = os.path.join(CAP, 'syslibs', os.path.basename(path))
            if not os.path.exists(local):
                return None, path
            if local not in cache:
                cache[local] = dynsyms(local)
            vaddr = addr - bases[path]
            syms = cache[local]
            if vaddr in syms:
                return syms[vaddr], path
            # A PLT target can be an alias a few bytes into the symbol only for
            # ifunc thunks; anything else that misses is reported, not guessed.
            return None, path
        return None, None

    objects = [
        ('liblime.so', 'liblime.got', 393),
        ('libApplicationMain.so', 'libApplicationMain.got', 161),
    ]
    print('/* Generated by capture/name_got.py -- do not edit by hand. */')
    print('/* PLT slots PairIP fills at load time on Android, named from a')
    print(' * donor process of Tightrope Theatre 1.0.5 arm64-v8a. */')
    print('')
    print('#include "tr.h"')
    print('')
    print('typedef struct { unsigned short slot; const char *name; }'
          ' tr_plt_ent;')
    for soname, gotfile, n in objects:
        got = open(os.path.join(CAP, gotfile), 'rb').read()
        rows, unknown = [], 0
        for i in range(3, 3 + n):
            v, = struct.unpack_from('<Q', got, i * 8)
            if not v:
                # The donor's loader left this slot at zero, so Android never
                # calls through it either.  Record it explicitly: a NULL name
                # means "intentionally empty", not "we failed to name it".
                rows.append((i, None))
                continue
            sym, path = name_of(v)
            if sym:
                rows.append((i, sym))
            else:
                unknown += 1
                print('/* slot %d -> %#x in %s: no symbol */'
                      % (i, v, path or '?'), file=sys.stderr)
        var = soname.split('.')[0].lower()
        print('')
        print('/* %s: %d of %d slots named, %d unresolved */'
              % (soname, len(rows), n, unknown))
        print('static const tr_plt_ent tr_%s_plt[] = {' % var)
        for slot, sym in rows:
            if sym is None:
                print('    { %4d, NULL },   /* zero on Android too */' % slot)
            else:
                print('    { %4d, "%s" },' % (slot, sym))
        print('};')

main()
