#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
"""nx-port-status -- relatorio SOMENTE-LEITURA da geracao de cada port.

Onda v2 (AUD-27): a politica "port historico fica preso ao contrato que
aprovou" e' correta, mas nada tornava a divida visivel -- responder "quais
ports estao em contrato antigo, quais tem nxrelease, qual versao de launcher"
exigia abrir 200 pastas. Este relatorio le e NUNCA escreve.

Uso:
    python3 framework/nxrelease/nx-port-status.py [--repo-root DIR] [--json]
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path


def launcher_generation(port_dir: Path) -> str:
    for launcher in sorted(port_dir.glob("*.sh")):
        try:
            head = launcher.read_text(encoding="utf-8", errors="replace")[:4096]
        except OSError:
            continue
        match = re.search(r"generated by nxbootstrap ([0-9]+(?:\.[0-9]+)*)", head)
        if match:
            return match.group(1)
        if "NXBOOTSTRAP_VERSION" in head or "nxbootstrap" in head:
            return "library-era"
    return "-"


def port_row(port_dir: Path) -> dict:
    row = {
        "port": port_dir.name,
        "launcher": launcher_generation(port_dir),
        "nxrelease": "-",
        "nxextract": "-",
        "version": "-",
    }
    version = port_dir / "version.txt"
    if version.is_file():
        row["version"] = version.read_text(encoding="utf-8",
                                           errors="replace").strip()[:16]
    manifest = port_dir / "nxrelease.json"
    if manifest.is_file():
        try:
            data = json.loads(manifest.read_text(encoding="utf-8"))
            row["nxrelease"] = str(
                data.get("package", {}).get("launcher_contract", {})
                .get("version", "?"))
        except (ValueError, OSError):
            row["nxrelease"] = "invalid-json"
    nxev = port_dir / "nxextract-version.txt"
    if nxev.is_file():
        row["nxextract"] = nxev.read_text(encoding="utf-8",
                                          errors="replace").strip()[:16]
    return row


TAXONOMY_RELATIVE = "framework/catalog/port-taxonomy-v1.json"
STATUS_ORDER = ("publicado", "completo", "jogavel", "em-andamento",
                "parado", "nogo", "nao-triado")
STATUS_TITLES = {
    "publicado": "FINALIZADOS E DISTRIBUÍDOS (R2 é PRIVADO — backup; público só com ordem, #22b)",
    "completo": "COMPLETOS no device (aguardando publicação/universal)",
    "jogavel": "JOGÁVEIS (com pendências)",
    "em-andamento": "EM ANDAMENTO",
    "parado": "PARADOS",
    "nogo": "NO-GO (não retriar — motivo anotado)",
    "nao-triado": "NÃO TRIADOS",
}


def load_taxonomy(root: Path) -> dict:
    path = root / TAXONOMY_RELATIVE
    if not path.is_file():
        return {}
    data = json.loads(path.read_text(encoding="utf-8"))
    return data.get("ports", {})


def render_index(taxonomy: dict, root: Path) -> str:
    lines = [
        "# Índice de ports — separado por STATUS, agrupado por engine",
        "",
        "> GERADO por `framework/nxrelease/nx-port-status.py --write-index` a",
        "> partir de `framework/catalog/port-taxonomy-v1.json`. NÃO editar à",
        "> mão: o gate do catalog reprova a bateria se este arquivo divergir",
        "> da taxonomia — é assim que ele fica SEMPRE atualizado.",
        "",
    ]
    by_status = {}
    for slug in sorted(taxonomy):
        entry = taxonomy[slug]
        by_status.setdefault(entry.get("status", "nao-triado"),
                             []).append((slug, entry))
    for status in STATUS_ORDER:
        items = by_status.get(status)
        if not items:
            continue
        lines.append("## %s — %d port(s)" % (STATUS_TITLES[status],
                                             len(items)))
        lines.append("")
        by_engine = {}
        for slug, entry in items:
            by_engine.setdefault(entry.get("engine", "desconhecido"),
                                 []).append((slug, entry))
        for engine in sorted(by_engine):
            lines.append("### %s" % engine)
            for slug, entry in by_engine[engine]:
                note = entry.get("note", "")
                integration = entry.get("integration", "")
                suffix = " — %s" % note if note else ""
                lines.append("- [`%s`](%s/) (%s)%s" %
                             (slug, slug, integration, suffix))
            lines.append("")
    lines.append("---")
    total = len(taxonomy)
    counts = ", ".join("%s=%d" % (st, len(by_status.get(st, [])))
                        for st in STATUS_ORDER if by_status.get(st))
    lines.append("Total: %d ports (%s)" % (total, counts))
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-root", default=None)
    parser.add_argument("--json", action="store_true")
    parser.add_argument("--status", help="filtra por status da taxonomia")
    parser.add_argument("--engine", help="filtra por engine da taxonomia")
    parser.add_argument("--write-index", action="store_true",
                        help="regenera ports/INDEX.md a partir da taxonomia")
    parser.add_argument("--check-index", action="store_true",
                        help="falha (rc=3) se ports/INDEX.md divergir do gerado")
    args = parser.parse_args()

    root = Path(args.repo_root) if args.repo_root else \
        Path(__file__).resolve().parents[2]
    ports_dir = root / "ports"
    if not ports_dir.is_dir():
        print("nx-port-status: ports/ nao encontrado em %s" % root,
              file=sys.stderr)
        return 2

    taxonomy = load_taxonomy(root)
    rows = [port_row(p) for p in sorted(ports_dir.iterdir()) if p.is_dir()]
    for row in rows:
        entry = taxonomy.get(row["port"], {})
        row["status"] = entry.get("status", "nao-triado")
        row["engine"] = entry.get("engine", "desconhecido")
        row["integration"] = entry.get("integration", "desconhecido")
        row["note"] = entry.get("note", "")
    if args.status:
        rows = [r for r in rows if r["status"] == args.status]
    if args.engine:
        rows = [r for r in rows if r["engine"].startswith(args.engine)]
    if args.write_index or args.check_index:
        text = render_index(taxonomy, root)
        index_path = ports_dir / "INDEX.md"
        if args.check_index:
            current = index_path.read_text(encoding="utf-8") \
                if index_path.is_file() else ""
            if current != text:
                print("nx-port-status: ports/INDEX.md esta' DESATUALIZADO "
                      "(rode --write-index e commite)", file=sys.stderr)
                return 3
            print("nx-port-status: INDEX.md em dia com a taxonomia")
            return 0
        index_path.write_text(text, encoding="utf-8")
        print("nx-port-status: ports/INDEX.md regenerado")
        return 0
    if args.json:
        json.dump(rows, sys.stdout, ensure_ascii=False, indent=1)
        print()
        return 0

    totals = {}
    print("%-24s %-10s %-10s %-10s %-10s" %
          ("port", "versao", "launcher", "contrato", "nxextract"))
    for row in rows:
        totals[row["launcher"]] = totals.get(row["launcher"], 0) + 1
        print("%-24s %-10s %-10s %-10s %-10s" %
              (row["port"][:24], row["version"], row["launcher"],
               row["nxrelease"], row["nxextract"]))
    print()
    print("geracoes de launcher: " + ", ".join(
        "%s=%d" % (k, v) for k, v in sorted(totals.items())))
    print("total de ports: %d (relatorio somente-leitura; nada foi alterado)"
          % len(rows))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
