FROM debian@sha256:58ce6f1271ae1c8a2006ff7d3e54e9874d839f573d8009c20154ad0f2fb0a225

ENV DEBIAN_FRONTEND=noninteractive

RUN printf "%s\n" \
        "deb [trusted=yes] http://archive.debian.org/debian buster main" \
        "deb [trusted=yes] http://archive.debian.org/debian-security buster/updates main" \
        > /etc/apt/sources.list \
    && apt-get -o Acquire::Check-Valid-Until=false \
        -o Acquire::AllowInsecureRepositories=true update -qq \
    && apt-get install -y -qq --allow-unauthenticated --no-install-recommends \
        gcc-aarch64-linux-gnu \
        libc6-dev-arm64-cross \
        binutils-aarch64-linux-gnu \
    && rm -rf /var/cache/apt/archives/* /var/lib/apt/lists/*

WORKDIR /src
