#!/usr/bin/env python3
"""Hermetic release gate for the Dead Trigger compatibility port."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
import re
import subprocess
import sys
import tempfile


PORT = Path(__file__).resolve().parents[1]
REPO = PORT.parents[1]
ELF = PORT / "build/deadtrigger-nextos"


def require(value: bool, message: str) -> None:
    if not value:
        raise AssertionError(message)


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def no_duplicates(pairs):
    result = {}
    for key, value in pairs:
        require(key not in result, f"duplicate JSON key: {key}")
        result[key] = value
    return result


def load_json(path: Path):
    return json.loads(path.read_text(encoding="utf-8"),
                      object_pairs_hook=no_duplicates)


def run(*argv: str) -> str:
    result = subprocess.run(argv, text=True, stdout=subprocess.PIPE,
                            stderr=subprocess.PIPE, check=False)
    require(result.returncode == 0,
            f"{' '.join(argv)} failed ({result.returncode})\n"
            f"{result.stdout}\n{result.stderr}")
    return result.stdout


def check_launcher() -> None:
    nxport = load_json(PORT / "nxport.json")
    require(nxport["schema_version"] == 2 and nxport["id"] == "deadtrigger",
            "nxport identity/schema drift")
    require(nxport["executable"] == "deadtrigger-nextos",
            "public executable name drift")
    require(nxport["nxextract"] == {"mode": "yes", "version": "1.2.6"},
            "NXExtract contract drift")
    for capability in (
        "host.portmaster", "host.aarch64-libs", "graphics.window",
        "graphics.gles2", "graphics.egl", "graphics.egl-config",
        "graphics.drawable", "audio.output-open",
        "input.controller-mapping", "input.controller-api",
    ):
        require(capability in nxport["required_capabilities"],
                f"missing capability: {capability}")

    launcher = (PORT / "Dead Trigger.sh").read_text(encoding="utf-8")
    require("generated by nxbootstrap 0.6.5" in launcher,
            "launcher is not nxbootstrap 0.6.5")
    for token in ("flock -n 9", 'wait "$game_pid"', "nxbootstrap_finish",
                  "pm_finish", "nxextract-runtime-env.sh",
                  '"/storage/.config/PortMaster"',
                  'NXCOMPAT_PORTMASTER_DIR="$controlfolder"'):
        require(token in launcher, f"launcher guarantee missing: {token}")
    for retired in ("deadtrigger-nextos.sh", "run.sh", "nxbootstrap.sh",
                    "nxdeployment.json"):
        require(not (PORT / retired).exists(),
                f"retired launcher remains: {retired}")

    generator = REPO / "framework/nxbootstrap/tools/generate-port.py"
    with tempfile.TemporaryDirectory(prefix="deadtrigger-launcher-") as temp:
        run(sys.executable, str(generator), str(PORT / "nxport.json"),
            "--output", temp)
        generated = Path(temp) / "Dead Trigger.sh"
        require(generated.read_bytes() ==
                (PORT / "Dead Trigger.sh").read_bytes(),
                "generated launcher is stale")


def check_recipe() -> None:
    recipe = load_json(PORT / "extractor.json")
    require(recipe["input"]["packages"] ==
            ["com.madfingergames.deadtrigger"], "package pin drift")
    require(recipe["hooks"] == [] and
            set(recipe["commit"]) == {"assets", "lib"},
            "transaction contract drift")
    assets = recipe["extract"][0]["validate"]
    require(assets["exact_files"] == 1441 and
            assets["exact_bytes"] == 306315658 and
            assets["tree_fingerprint"] ==
            "b66c8c7c473bae68dd717eebce991633e83bb33d8105e4e02bc066eb3c7f4ee1",
            "asset-tree pin drift")
    expected = {
        "android-native-loader":
            "c32a89d727bb920d125e50f1bdc4663e284af3afb5f737e3482fc06f1c6ebc73",
        "android-unity-player":
            "af3519ed16e3fdf5b85afae3b7477aa83ea370c353cd7352fdb77926aac75290",
        "android-il2cpp-runtime":
            "37c25b8fcdb0387c660fb33554c3e585aa13fd505b12bffff48816d91361efe9",
    }
    for rule in recipe["extract"][1:]:
        require(rule["validate"]["sha256"] == expected[rule["id"]],
                f"native payload pin drift: {rule['id']}")
    run(sys.executable, str(PORT / "nxextract/nxextract.py"),
        "recipe-check", "--recipe", str(PORT / "extractor.json"))


def check_native_contract() -> None:
    main = (PORT / "src/main.c").read_text(encoding="utf-8")
    order = (
        'dt_module_load("libmain.so")', "main_on_load(jni_get_vm()",
        "native_loader_load(jni_get_env()", "g_unity.init_jni(",
        "pthread_create(&unity_thread",
    )
    positions = [main.index(token) for token in order]
    require(positions == sorted(positions), "Android lifecycle order drift")
    for token in (
        "SDL_CONTROLLER_BUTTON_RIGHTSTICK", "inject_touch(0, cursor_x",
        "cursor_active = !dt_gamepad_gameplay_active()",
        "hypotf(horizontal, vertical)", "response * response",
        "right_x = 0.0f", "left_x = normalized_axis",
        "int r3_down = merged_button(",
        "int start_down = merged_button(",
        "int select_down = merged_button(",
        "cursor_touch_stage <= 9", "dt_sdl_video_size(",
        "dt_android_set_size(video_width, video_height)",
        "SDL_GameControllerGetBindForButton(",
        "SDL_GameControllerGetBindForAxis(",
        "SDL_JoystickNumButtons(joystick) >= 12",
        "SDL_JoystickGetButton(", "SDL_JOYBUTTONDOWN",
        "int a_pressed = a_press_pending",
        'cursor_touch_source = r3_pressed ? "R3" : "A/Cross"',
    ):
        require(token in main, f"contextual cursor contract missing: {token}")
    require("controller_has_classic_12_button_layout" in main and
            "SDL_CONTROLLER_BUTTON_LEFTSHOULDER, 4" in main and
            "SDL_CONTROLLER_BUTTON_RIGHTSHOULDER, 5" in main and
            "SDL_CONTROLLER_BUTTON_BACK, 8" in main and
            "SDL_CONTROLLER_BUTTON_START, 9" in main,
            "capability-based classic 12-button recovery missing")
    require("SDL_CONTROLLER_AXIS_TRIGGERRIGHT, g_r2_raw_fallback, 7" in
            main and
            "SDL_CONTROLLER_AXIS_TRIGGERLEFT, g_l2_raw_fallback, 6" in
            main and
            "SDL_CONTROLLER_BUTTON_RIGHTSTICK" in main,
            "capability-based L2/R2/R3 recovery missing")
    require("0300605b100800000100000010010000" not in main and
            "Twin USB" not in main,
            "R3 recovery was hardcoded to a device identity")
    ordinal = (PORT / "src/pad_ordinal_fix.h").read_text(encoding="utf-8")
    require("pad_ord_has_complete_portmaster_layout" in ordinal and
            "SDL_CONTROLLER_BUTTON_RIGHTSTICK, 9" in ordinal and
            "SDL_CONTROLLER_AXIS_TRIGGERLEFT, 10" in ordinal and
            "SDL_CONTROLLER_AXIS_TRIGGERRIGHT, 11" in ordinal,
            "complete PortMaster mapping is not protected from ordinal fix")
    event_block = main[main.index("SDL_CONTROLLERBUTTONDOWN"):
                       main.index("dt_framework_poll_input")]
    require("start_down = pressed" not in event_block and
            "select_down = pressed" not in event_block,
            "exit chord regressed to event-only button tracking")
    require("button == SDL_CONTROLLER_BUTTON_A && pressed" in event_block and
            "level |= 1u << 10; /* Action */" in main and
            "dt_gamepad_publish(left_x, left_y, right_x, right_y, buttons" in
            main,
            "A/Cross menu mirror no longer preserves native semantic A")

    gamepad = (PORT / "src/gamepad_dt.c").read_text(encoding="utf-8")
    require("g_gameplay_axis_millis" in gamepad and
            "input >= DT_INPUT_MOVE_RIGHT" in gamepad,
            "gameplay context lacks native-axis evidence")
    loader = (PORT / "src/loader.c").read_text(encoding="utf-8")
    require('snprintf(path, path_size, "%s/lib/%s", g_root' in loader and
            "if (access(path, R_OK) == 0)" in loader,
            "canonical lib fallback missing")
    shims = (PORT / "src/shims.c").read_text(encoding="utf-8")
    require('ADD("fstat", dt_fstat)' in shims and
            'ADD("fstat64", dt_fstat)' in shims,
            "portable fstat bridge missing")
    sem_shim = (PORT / "src/sem_shim_dt.c").read_text(encoding="utf-8")
    require("normalize_timespec" in sem_shim and
            "normalized->tv_nsec >= 1000000000L" in sem_shim and
            "if (rc != 0)" in sem_shim and "errno = rc" in sem_shim,
            "Unity scene-transition timed-wait recovery missing")
    build = (PORT / "build_universal.sh").read_text(encoding="utf-8")
    require('$PORT_DIR/src/sem_shim_dt.c' in build and
            '$SHARED_LOADER/sem_shim.c' not in build,
            "public build does not select the Dead Trigger semaphore shim")
    media = (PORT / "src/media_dt.c").read_text(encoding="utf-8")
    for token in (
        "const int can_present = !sdl_active",
        "g_original_start_video(instance, method)",
        "g_stop_video(instance, g_stop_video_method)",
        "frame_width = dt_android_width()",
        "frame_height = dt_android_height()",
    ):
        require(token in media, f"intro backend contract missing: {token}")
    require(media.index("const int can_present") <
            media.index("extract_intro(video"),
            "intro extraction occurs before capability preflight")
    require(media.index("g_original_start_video(instance, method)") <
            media.index("g_stop_video(instance, g_stop_video_method)"),
            "native intro StartVideo/StopVideo order drift")


def check_elf() -> None:
    require(ELF.is_file(), "public ELF missing")
    require("AArch64" in run("readelf", "-hW", str(ELF)),
            "public ELF is not AArch64")
    dynamic = run("readelf", "-dW", str(ELF))
    require("(RPATH)" not in dynamic and "(RUNPATH)" not in dynamic,
            "RPATH/RUNPATH present")
    program = run("readelf", "-lW", str(ELF))
    require(not any("LOAD" in line and "RWE" in line
                    for line in program.splitlines()), "RWE segment present")
    versions = run("readelf", "--version-info", str(ELF))
    glibc = [(int(a), int(b)) for a, b in
             re.findall(r"GLIBC_(\d+)\.(\d+)", versions)]
    require(glibc and max(glibc) <= (2, 17),
            "public ELF exceeds its GLIBC_2.17 contract")
    needed = sorted(re.findall(r"Shared library: \[([^]]+)\]", dynamic))
    require(needed == sorted([
        "libSDL2-2.0.so.0", "libEGL.so", "libGLESv2.so", "libc.so.6",
        "libdl.so.2", "libgcc_s.so.1", "libm.so.6", "libpthread.so.0",
        "libz.so.1",
    ]), f"DT_NEEDED drift: {needed}")
    symbols = run("nm", "-D", str(ELF))
    for symbol in ("nxcompat_probe", "nxinput_create",
                   "nxaudio_classify_backend", "dt_framework_preflight"):
        require(re.search(rf"\b{symbol}$", symbols, re.MULTILINE) is not None,
                f"framework symbol missing: {symbol}")


def check_release() -> None:
    release = load_json(PORT / "nxrelease.json")
    require(release["package"]["version"] == "1.1.1",
            "release version drift")
    require(release["package"]["launcher_contract"]["config_sha256"] ==
            sha256(PORT / "nxport.json"), "nxport release pin stale")
    require(release["nxextract"]["recipe_sha256"] ==
            sha256(PORT / "extractor.json"), "extractor release pin stale")
    for entry in release["files"]:
        source = PORT / entry["source"]
        require(source.is_file() and not source.is_symlink(),
                f"unsafe/missing release source: {entry['source']}")
        require(entry["sha256"] == sha256(source),
                f"stale release hash: {entry['source']}")
        require(not re.search(r"\.(apk|apkm|apks|xapk|obb|so)$",
                              entry["target"], re.IGNORECASE),
                f"owner data entered release: {entry['target']}")

    status = load_json(PORT / "references/migration-status-v1.json")
    adapter = load_json(PORT / "references/adapter-contract-v1.json")
    require(status["physical_device_evidence"] is True and
            status["release_blocker"]["active"] is False,
            "migration status is not release ready")
    require(adapter["physical_device_evidence"] is True and
            adapter["release_ready"] is True,
            "adapter status is not release ready")

    public_text = "\n".join(
        path.read_text(encoding="utf-8", errors="strict")
        for path in PORT.rglob("*")
        if path.is_file() and path.suffix in {".md", ".txt", ".json", ".sh"}
        and not any(part in {"game", "payload", "dump_out", "build",
                             "tests", "gamedata"}
                    for part in path.relative_to(PORT).parts)
    )
    for pattern in (r"192\.168\.", r"/home/", r"root@"):
        require(re.search(pattern, public_text, re.IGNORECASE) is None,
                f"private literal in public text: {pattern}")


def main() -> int:
    check_launcher()
    check_recipe()
    check_native_contract()
    check_elf()
    check_release()
    print("DEAD TRIGGER RELEASE CONTRACT: PASS")
    print("physical_device_evidence=1 proprietary_payload_packaged=0")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
